import React, {useEffect, useState, useRef} from 'react'
import {modules} from './applicationModules'
import './application.css'

type Props={id:string;module:string;Game:React.ComponentType<any>}
const fieldNames:Record<string,string>={surname:'姓氏',unread:'未读',contact_time:'最近联系',timestamp:'时间序号',members:'成员人数',size:'字节数',age_days:'距今 / 天',duration:'时长 / 秒',rating:'评分',plays:'播放次数',year:'发行年份',artist:'歌手',publisher:'来源',comments:'评论数',tag_count:'标签数',words:'字数',context:'上下文长度',price:'价格',sales:'销量',stock:'库存',amount:'金额',account:'收款账号',balance:'余额',transactions:'交易次数',same_day:'最近两笔交易同日',departure:'出发时间序号',transfers:'换乘次数',verdict:'判题结果',samples:'样例数',number:'题号',lines:'代码行数',runtime_ms:'耗时 / ms',pass_rate:'通过率',category:'队列标签',like_rate:'点赞率',completed:'播放完成'}
const fields:Record<string,string[]>={chat:['surname','unread','contact_time','timestamp','members','size','age_days'],im:['unread','contact_time'],music:['duration','rating','plays','year','artist'],news:['publisher','timestamp','comments','tag_count'],media:['duration','rating','comments','timestamp','completed','category','like_rate'],blog:['words','tag_count','timestamp'],studio:['context','price'],travel:['duration','price','transfers','departure'],shop:['rating','sales','comments','price','stock'],bank:['amount','account','balance','transactions','same_day','timestamp'],code:['verdict','samples','number','lines','runtime_ms','pass_rate','timestamp']}
const taskFields:Record<number,string[]>={5:[],6:[],7:['unread','timestamp'],8:['members'],9:['surname','contact_time','unread'],10:['unread'],11:['size'],12:['unread','timestamp'],13:[],14:['unread','age_days'],15:['contact_time','unread'],16:[],22:['duration','plays'],23:['publisher'],24:['publisher'],25:['duration'],26:['rating','comments'],27:['rating','plays'],28:['year','duration','artist'],29:['timestamp'],30:['tag_count','comments'],31:['duration','like_rate','timestamp'],32:['rating','duration'],33:[],34:['completed'],35:['duration','category'],38:['words'],39:[],40:['timestamp','words'],41:['context','price'],42:['tag_count'],43:[],47:['duration','price','transfers'],48:['rating','sales','comments'],49:['amount'],50:['balance','transactions'],51:['price','duration','departure'],52:['rating','price','stock'],53:['amount','timestamp'],54:['price','transfers'],55:[],56:['account','amount'],57:['balance','same_day'],61:['verdict','runtime_ms'],62:['samples','number'],63:['number','pass_rate'],64:['timestamp','lines'],65:[]}
const parameters:Record<number,string[]>={1:['recipient'],3:['recipient'],4:['recipient'],13:['keyword','recipient'],16:['fixed_reply'],22:['threshold'],23:['publisher'],26:[],32:['threshold'],33:['keyword'],35:['tag'],38:['threshold'],42:['letter'],43:['recipient'],48:['threshold'],49:['text_threshold'],54:['threshold'],55:['tag'],56:['letter','threshold'],57:['threshold'],60:['rename_targets'],65:['function','code_threshold']}
const parameterNames:Record<string,string>={recipient:'收件人',keyword:'指定词',fixed_reply:'固定回复',threshold:'阈值',publisher:'指定媒体',tag:'指定标签',letter:'指定字母',text_threshold:'备注长度阈值',function:'指定函数',code_threshold:'代码长度阈值',rename_targets:'需重命名的变量'}
const collectionNames:Record<string,string>={'list-a':'播放列表甲',watchlist:'观看列表',history:'观看历史',favorites:'收藏',cart:'购物车',reading_list:'阅读清单'}
const saveNames:Record<number,string>={1:'发送消息',2:'保存昵称',3:'发送模板消息',4:'发送草稿',17:'保存显示名称',18:'创建播放列表',19:'保存文章标题',20:'保存标签文本',21:'重命名收藏夹',36:'保存文章标题',37:'保存提示词',44:'保存乘客姓名',45:'保存商品备注',46:'保存转账备注',58:'提交代码',59:'保存答案',60:'保存代码'}
export function Application({id,module,Game}:Props){
 const config=modules[module as keyof typeof modules],credential=useRef(location.hash.slice(1))
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[pending,setPending]=useState(false),[draft,setDraft]=useState(''),[selection,setSelection]=useState<string[]>([]),[order,setOrder]=useState<string[]>([]),[tab,setTab]=useState(''),[focused,setFocused]=useState(''),[query,setQuery]=useState('')
 async function call(path:string,body?:unknown){const r=await fetch(`/api/runs/${id}${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${credential.current}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(typeof v.detail==='string'?v.detail:JSON.stringify(v.detail));return v}
 useEffect(()=>{call('').then(d=>{setData(d);setOrder(d.state.order||[]);setTab(d.state.task_id===34?config.tabs[1]:config.tabs[0]);setFocused(d.state.items?.[0]?.id||'')}).catch(e=>setError(String(e)))},[])
 async function mutate(op:string,target='',value='',ids:string[]=[]){setPending(true);try{if(value==='复制'){const text=data.state.domain.objects[target].text;await navigator.clipboard.writeText(text)}const d=await call('/commands',{epoch:data.epoch,action_id:crypto.randomUUID(),op,target,value,ids});setData(d);setError('')}catch(e){setError(String(e))}finally{setPending(false)}}
 if(!data)return <main className="application-loading">{error||'正在打开应用…'}</main>
 const s=data.state,d=s.domain,t=s.task_id,sort=[12,28,35].includes(t),multi=[15,30].includes(t),active=d?.objects[focused]
 const ordered=sort?order.map(i=>s.items.find((x:any)=>x.id===i)):s.items
 const displayed=ordered?.filter((x:any)=>t!==34||d.collections.watchlist.includes(x.id)).filter((x:any)=>`${x.name} ${x.text}`.toLowerCase().includes(query.toLowerCase()))
 const objectName=(id:string)=>id==='self'?'主账户':d?.objects[id]?.name||id
 const summaries=d?[...d.messages.filter((m:any)=>m.sender==='self').map((m:any)=>`发送至 ${objectName(m.recipient)}：${m.body}${m.attachment?' · 附件 '+objectName(m.attachment):''}`),...d.artifacts.map((a:any)=>`${({publication:'已发布文章',document:'已保存内容',submission:'已提交代码',booking:'已确认预订'} as any)[a.kind]||a.kind} · ${objectName(a.target)}${a.body?' · '+a.body:''}`),...Object.entries(d.collections).filter(([,v])=>(v as any[]).length).map(([k,v])=>`${collectionNames[k]||k}：${(v as string[]).map(objectName).join('、')}`),...Object.entries(d.memberships).map(([k,v])=>`群组 ${objectName(k)}：${(v as string[]).map(objectName).join('、')}`),...d.ledger.map((x:any)=>`${objectName(x.account)} ${x.cents>0?'+':''}${(x.cents/100).toFixed(2)} → ${objectName(x.counterparty)}`)]:[]
 function choose(i:string){setSelection(prev=>multi?(prev.includes(i)?prev.filter(x=>x!==i):[...prev,i]):[i])}
 function move(i:number,delta:number){const next=[...order];if(i+delta<0||i+delta>=next.length)return;[next[i],next[i+delta]]=[next[i+delta],next[i]];setOrder(next)}
 return <div className={`application app-${module}`} style={{'--app-color':config.color} as React.CSSProperties}>
  <aside className="application-nav"><strong>{config.title}</strong><small>{config.subtitle}</small><nav>{config.tabs.map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</nav><div className="application-account">演示账户<br/><span>数据独立 · 可重置</span></div></aside>
  <main className="application-main"><header><div><small>{tab}</small><h1>{s.title.split('：').slice(1).join('：')||s.title}</h1></div><span className="app-connected">● 已连接</span></header>{error&&<div role="alert" className="error">{error}</div>}
  {s.game?<Game state={s} pending={pending} error={error} mutate={mutate}/>:<>
   <details className="task-parameters" open><summary>任务资料</summary><div>{(parameters[t]||[]).map(key=><span key={key}>{parameterNames[key]}：{Array.isArray(s.source[key])?s.source[key].join('、'):s.source[key]}　</span>)}{![1,3,4].includes(t)&&<span>并列时按初始列表顺序处理；排序保留同类对象的相对顺序。</span>}</div></details>
   {s.type==='T'?<section className="application-editor"><div className="source-document"><h2>待处理资料</h2><pre>{s.source.text}</pre>{t===18&&<p>歌手 {s.source.artist} · 数量 {s.source.count} · 日期 {s.source.date}<br/>字段间用下划线连接，三字段循环排列。</p>}{t===20&&<p>标签：{s.source.tags.join('、')}</p>}{t===44&&<p>姓 {s.source.surname} · 名 {s.source.given_name}</p>}{t===45&&<p>商品 {s.source.text} · 数量 {s.source.quantity}</p>}{t===19&&<p>来源简称 {s.source.publisher_short}</p>}<p className="muted">按教程中的规则填写右侧内容。</p></div><div className="document-editor"><label>编辑内容<textarea aria-label="编辑内容" spellCheck={false} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();const a=e.currentTarget.selectionStart,b=e.currentTarget.selectionEnd;setDraft(draft.slice(0,a)+'\t'+draft.slice(b));requestAnimationFrame(()=>{const el=document.querySelector('textarea')!;el.selectionStart=el.selectionEnd=a+1})}}}/></label><button disabled={pending} onClick={()=>mutate('save','target',draft)}>{saveNames[t]}</button>{s.outputs.target!==undefined&&<div className="application-saved"><strong>已写入应用</strong><pre>{s.outputs.target}</pre></div>}</div></section>:
    <><div className="application-toolbar"><input aria-label="搜索对象" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或内容…"/><span>{s.items.length} 个对象</span></div><div className="application-records"><section className="record-list">{displayed.map((item:any,index:number)=><article data-object-id={item.id} key={item.id} className={focused===item.id?'focused':''} onClick={()=>setFocused(item.id)}><div className="record-title"><b>{item.name}</b><small>{item.id}</small></div><p>{['code','studio'].includes(module)?item.code:item.text}</p><div className="record-properties">{(taskFields[t]||fields[module]||[]).map(f=><span key={f}>{fieldNames[f]} <b>{typeof item[f]==='boolean'?(item[f]?'是':'否'):item[f]}</b></span>)}</div>{item.tags.length>0&&<p>标签：{item.tags.join(' / ')}</p>}
     <div className="record-controls">{s.type==='C'?<label>分类 <select aria-label={`分类 ${item.id}`} value={d.objects[item.id].label} disabled={pending} onChange={e=>mutate('label',item.id,e.target.value)}><option value="">未标注</option>{s.options.map((o:string)=><option key={o}>{o}</option>)}</select></label>:sort?<><button onClick={()=>move(index,-1)} disabled={index===0}>↑ 上移</button><button onClick={()=>move(index,1)} disabled={index===s.items.length-1}>↓ 下移</button></>:s.type==='S'||t===15?<button onClick={()=>choose(item.id)}>{selection.includes(item.id)?'✓ 已选择':'选择'}</button>:s.options.map((op:string)=><button disabled={pending} key={op} onClick={()=>mutate('action',item.id,op)}>{op}</button>)}</div>
     {d.checks.filter((x:any)=>x.target===item.id).map((x:any,i:number)=><p className="check-result" key={i}>语法检查：{x.passed?'通过':'未通过'}</p>)}
     <div className="object-status">{['read','starred','archived','pinned','muted','hidden','published','reminder'].filter(f=>d.objects[item.id][f]).map(f=><span key={f}>{({read:'已读',starred:'已收藏',archived:'已归档',pinned:'已置顶',muted:'已静音',hidden:'已隐藏',published:'已发布',reminder:'提醒开启'} as any)[f]}</span>)}</div>
    </article>)}</section><aside className="record-inspector"><h2>{active?.name||'对象详情'}</h2><pre>{active?.text}</pre>{module==='bank'&&<p>可用余额：{(d.balances.self/100).toFixed(2)}</p>}<h3>应用记录</h3>{summaries.length?summaries.map((line,i)=><p className="domain-event" key={i}>{line}</p>):<p className="muted">业务操作将在这里显示。</p>}</aside></div>{(s.type==='S'||t===15||sort)&&<footer className="application-confirm"><span>{sort?'列表顺序可编辑':`已选择 ${selection.length} 项`}</span><button disabled={pending} onClick={()=>mutate(sort?'order':t===15?'invite':'select','','',sort?order:selection)}>{t===15?'创建群聊并邀请':'确认操作'}</button>{s.selection.length>0||s.members.length>0?<span>已确认</span>:null}</footer>}</>}
   {s.type==='T'&&summaries.length>0&&<section className="application-journal"><h2>应用记录</h2>{summaries.map((line,i)=><p key={i}>{line}</p>)}</section>}
  </>}
  </main>
 </div>
}
