# Generated by Django 5.2.4 on 2025-07-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pure_name", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("url", models.URLField()),
                ("description", models.TextField()),
                ("hot_songs", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name="comment",
            name="blog",
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("pure_name", models.CharField(max_length=200)),
                ("image", models.URLField()),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("date", models.CharField(blank=True, max_length=50)),
                ("lyrics", models.TextField(blank=True)),
                (
                    "artists",
                    models.ManyToManyField(related_name="songs", to="blog.artist"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
