import {useState} from 'react';
import {Frame,PageHead,Notice,type ProductAPI} from './kit';

const values=(x:any):any[]=>Object.values(x);
const money=(c:number)=>(c/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const readFile=(f:any)=>f?new TextDecoder().decode(Uint8Array.from(atob(f.content),c=>c.charCodeAt(0))):'';
const send=(api:ProductAPI,op:string,target='',data={})=>api.mutate(op,target,JSON.stringify(data));
const currentRows=(w:any)=>w.batch_bills.map((bill:string)=>({bill,transfer:w.bill_links[bill]||'',reason:w.bill_links[bill]?'':w.unpaid_reason}));
const signature=(rows:any[])=>JSON.stringify(rows.map(r=>[r.bill,r.transfer,r.reason]));

function TransferForm({api,bill,done}:{api:ProductAPI,bill:any,done:(id:string)=>void}) {
  const w=api.s.world,[payer,setPayer]=useState(''),[payee,setPayee]=useState(''),[amount,setAmount]=useState(''),[memo,setMemo]=useState(''),[review,setReview]=useState(false);
  const match=/^(\d+)(?:\.(\d{1,2}))?$/.exec(amount.trim());
  const cents=match?Number(match[1])*100+Number((match[2]||'').padEnd(2,'0')):0;
  const valid=!!payer&&!!payee&&Number.isSafeInteger(cents)&&cents>0&&cents<=api.d.balances[payer]&&memo.trim().length>0&&memo.length<=200;
  const account=w.accounts.find((a:any)=>a.id===payer),person=api.d.objects[payee],already=values(w.transfers).some(t=>t.bill===bill.id);
  return <><PageHead title={review?'确认付款信息':'填写转账资料'} description={bill.id+' · '+bill.project+' · '+bill.purpose}/><section className="payment-panel payment-form"><p>账单要求：{api.d.objects[bill.payee].record_code} · {w.accounts.find((a:any)=>a.id===bill.payer).name} · ¥{money(bill.cents)}</p>{review?<><h2>请核对每项信息</h2><dl className="payment-facts"><dt>账单编号</dt><dd>{bill.id}</dd><dt>付款账户</dt><dd>{account.name} · {account.number}</dd><dt>供应商编号</dt><dd>{person.record_code}</dd><dt>收款人</dt><dd>{person.name} · {person.company}</dd><dt>收款账号</dt><dd>{person.account}</dd><dt>付款金额</dt><dd>¥{money(cents)}</dd><dt>转账备注</dt><dd>{memo}</dd><dt>手续费</dt><dd>¥0.00</dd></dl><p>确认后即在模拟账户入账，不能撤销；填错并已确认时须重置本轮。本环境不发生真实资金转移。</p><div className="product-actions"><button disabled={api.busy} onClick={()=>setReview(false)}>返回修改</button><button className="product-primary" disabled={api.busy||already||!valid} onClick={async()=>{const id='PAY-'+String(api.s.next_transfer||1).padStart(4,'0');if(await send(api,'transfer.execute','',{bill:bill.id,payer,payee,cents,memo}))done(id);}}>确认模拟付款</button></div></>:<><label>付款账户<select aria-label="付款账户" value={payer} onChange={e=>setPayer(e.target.value)}><option value="">请选择付款账户</option>{w.accounts.map((a:any)=><option key={a.id} value={a.id}>{a.name} · {a.number} · 可用 ¥{money(api.d.balances[a.id])}</option>)}</select></label><label>收款人<select aria-label="收款人" value={payee} onChange={e=>setPayee(e.target.value)}><option value="">请按供应商编号选择</option>{api.s.items.map((p:any)=>api.d.objects[p.id]).map((p:any)=><option key={p.id} value={p.id}>{p.record_code} · {p.name} · {p.company}</option>)}</select></label>{person&&<p className="payment-account">收款账号：{person.account} · {person.bank}</p>}<label>付款金额（元）<input aria-label="付款金额" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><button onClick={()=>setAmount((bill.cents/100).toFixed(2))}>填入账单金额</button><label>转账备注<input aria-label="转账备注" maxLength={200} value={memo} onChange={e=>setMemo(e.target.value)}/></label>{api.s.task_id===56&&<button onClick={()=>setMemo(bill.note)}>填入账单附言</button>}<p>{api.s.task_id===46?'请按视频格式填写核实后的完整收款账号。':'附言使用账单中给出的文字。'} 金额最多两位小数，手续费为零。</p>{amount&&!valid&&!memo&&<small>填写全部资料后可进入核对页。</small>}{already&&<p role="alert">此账单已付款，请查看交易明细，勿重复支付。</p>}<button className="product-primary" disabled={!valid||already||api.busy} onClick={()=>setReview(true)}>核对付款资料</button></>}</section></>;
}

function BillDetail({api,bill,prepare,download}:{api:ProductAPI,bill:any,prepare:()=>void,download:(id:string)=>void}) {
  const w=api.s.world,p=api.d.objects[bill.payee],account=w.accounts.find((a:any)=>a.id===bill.payer),[reference,setReference]=useState(w.bill_links[bill.id]||'');
  const payment=values(w.transfers).find(t=>t.bill===bill.id),link=w.bill_links[bill.id],inBatch=w.batch_bills.includes(bill.id);
  return <><PageHead title={bill.id+' · '+bill.purpose} description={bill.project+' · '+bill.batch+' 批次'}/><section className="payment-panel"><dl className="payment-facts"><dt>供应商编号</dt><dd>{p.record_code}</dd><dt>供应商</dt><dd>{p.name} · {p.company}</dd><dt>指定付款账户</dt><dd>{account.name} · {account.number}</dd><dt>账单金额</dt><dd>¥{money(bill.cents)}</dd><dt>账单附言</dt><dd>{bill.note}</dd><dt>付款状态</dt><dd>{payment?'已付款 · '+payment.id:'尚未付款'}</dd><dt>回填状态</dt><dd>{link||'尚未关联回执'}</dd></dl><div className="product-actions"><a href={api.applicationLink?.('bank',{payee:bill.payee})}>查看收款资料 →</a><a href={api.applicationLink?.('im')}>查看团队付款通知 →</a>{inBatch&&<button className="product-primary" disabled={!!payment} onClick={prepare}>准备付款</button>}{payment&&<a href={api.applicationLink?.('bank',{transfer:payment.id})}>查看本账单付款回执 →</a>}</div></section>{inBatch&&<section className="payment-panel"><h2>回填付款编号</h2><p>请核对回执中的账单、收款人和金额。关联回执不会执行转账。</p><label>付款回执<select aria-label="付款回执" value={reference} onChange={e=>setReference(e.target.value)}><option value="">请选择付款编号</option>{values(w.transfers).map(t=><option key={t.id} value={t.id}>{t.id} · {t.bill} · ¥{money(t.cents)}</option>)}</select></label><div className="product-actions"><button disabled={api.busy||!reference} onClick={()=>send(api,'bill.link',bill.id,{transfer:reference})}>保存付款关联</button><button disabled={api.busy||!link} onClick={async()=>{if(await send(api,'bill.unlink',bill.id))setReference('');}}>清除付款关联</button>{link&&<button onClick={()=>download('transfer-'+link)}>下载关联回执</button>}</div></section>}</>;
}

function Reconciliation({api,download}:{api:ProductAPI,download:(id:string)=>void}) {
  const w=api.s.world,saved=w.report,[rows,setRows]=useState<any[]>(saved?.rows||w.batch_bills.map((bill:string)=>({bill,transfer:'',reason:''}))),[recipient,setRecipient]=useState('');
  const dirty=!saved||signature(rows)!==signature(saved.rows),stale=!!saved&&(signature(saved.rows)!==signature(currentRows(w))||w.accounts.some((a:any)=>!saved.body.includes('期末 '+(api.d.balances[a.id]/100).toFixed(2)+' 元')));
  const locked=!!w.receipts.length;
  function edit(id:string,key:string,value:string){setRows(old=>old.map(r=>r.bill===id?{...r,[key]:value}:r));}
  return <><PageHead title="十月付款对账清单" description="记录本期账单的已付与未付结果，并将账户余额与真实付款对应。"/><section className="payment-panel"><button disabled={locked} onClick={()=>setRows(currentRows(w))}>读取账单回填结果</button><div className="payment-table-wrap"><table className="payment-table"><thead><tr><th>账单与金额</th><th>付款编号</th><th>未付款原因</th><th>核对</th></tr></thead><tbody>{rows.map(row=>{const b=w.bills.find((b:any)=>b.id===row.bill);return <tr key={row.bill}><td><b>{b.id}</b><small>{b.project} · ¥{money(b.cents)}</small></td><td><select aria-label={'对账付款 '+b.id} disabled={locked} value={row.transfer} onChange={e=>edit(b.id,'transfer',e.target.value)}><option value="">未付款</option>{values(w.transfers).map(t=><option key={t.id} value={t.id}>{t.id} · {t.bill}</option>)}</select></td><td><input aria-label={'未付原因 '+b.id} disabled={locked} value={row.reason} onChange={e=>edit(b.id,'reason',e.target.value)}/></td><td><a href={api.applicationLink?.('bank',{bill:b.id})}>账单 {b.id}</a>{row.transfer&&<a href={api.applicationLink?.('bank',{transfer:row.transfer})}>回执 {row.transfer}</a>}</td></tr>;})}</tbody></table></div><div className="product-actions"><button className="product-primary" disabled={api.busy||locked} onClick={()=>send(api,'report.save','',{rows})}>保存对账清单</button>{saved&&<button disabled={api.busy||locked} onClick={()=>send(api,'report.delete')}>删除对账清单</button>}</div>{dirty&&<p>对账明细有待保存内容。</p>}{stale&&<p role="alert">账单或余额已经变化，请撤回通知并重新核对、保存清单。</p>}</section>{saved&&<section className="payment-panel"><h2>已保存的对账清单</h2><button onClick={()=>download('payment-report')}>下载对账清单</button><pre className="payment-document">{saved.body}</pre></section>}<section className="payment-panel"><h2>发送财务核对</h2><label>财务收件人<select aria-label="财务收件人" value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">请选择联系人</option>{w.people.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {p.role}</option>)}</select></label><div className="product-actions"><button disabled={api.busy||!recipient||dirty||stale||locked} onClick={()=>send(api,'report.send','',{recipient:Number(recipient)})}>发送对账清单</button><a href={api.applicationLink?.('im')}>打开团队付款消息 →</a></div>{w.receipts.map((r:any)=><div className="product-actions" data-payment-notice={r.id} key={r.id}><span>已发送给 {w.people.find((p:any)=>p.id===r.recipient).name} · {r.id}</span><button disabled={api.busy} onClick={()=>send(api,'receipt.withdraw',r.id)}>撤回对账通知</button></div>)}</section></>;
}

export function BankProjects({api}:{api:ProductAPI}) {
  const {s,d}=api,w=s.world,params=new URLSearchParams(location.search);
  const [page,setPage]=useState(params.has('bill')?'bill':params.has('payee')?'payee':params.has('transfer')?'receipt':params.has('report')?'report':params.has('file')?'file':'home');
  const [billId,setBillId]=useState(params.get('bill')||''),[payeeId,setPayeeId]=useState(params.get('payee')||''),[transferId,setTransferId]=useState(params.get('transfer')||''),[query,setQuery]=useState(''),[scope,setScope]=useState('current'),[error,setError]=useState('');
  const bill=w.bills.find((b:any)=>b.id===billId),payee=d.objects[payeeId],transfer=w.transfers[transferId],payees=s.items.map((p:any)=>d.objects[p.id]);
  function nav(p:string){setPage(p);setQuery('');setError('');api.clearNotice?.();}
  function openBill(id:string){setBillId(id);nav('bill');}
  async function download(id:string){try{await api.downloadFile?.(id,d.files[id].name);}catch(e){setError(String(e));}}
  const total=w.accounts.reduce((sum:number,a:any)=>sum+d.balances[a.id],0),newPayments=values(w.transfers).filter(t=>!s.world.opening_balances||t.id!=='PAY-H001');
  return <Frame brand="青禾账户" accent="#285ba5" page={page} navigate={nav} tabs={[["home","账户总览"],["bills","账单中心"],["payees","收款人名册"],["accounts","付款账户"],["transactions","交易明细"],...(s.task_id===56?[["report","对账清单"] as [string,string]]:[])]} tools={<><a href={api.applicationLink?.('im')}>团队付款通知 →</a><span className="bank-sandbox">模拟账户 · 不连接真实资金</span></>}><main className="product-main payment-workspace"><Notice api={api}/>{error&&<p role="alert">{error}</p>}
    {page==='home'&&<><PageHead eyebrow="GOOD MORNING, YUAN" title="你好，周予安" description="核对每张账单，让每一笔付款都有据可查。"/><div className="bank-overview"><section className="bank-balance"><span>付款账户可用余额（元）</span><h1>¥{money(total)}</h1><p>三个独立账户 · 模拟资金</p><div><button onClick={()=>nav('bills')}>处理本期账单 ↗</button><button onClick={()=>nav('transactions')}>查看明细 →</button></div></section><section className="bank-summary"><h3>本期付款</h3><button onClick={()=>nav('bills')}>待核对账单 <b>{w.batch_bills.length} 张 →</b></button><button onClick={()=>nav('transactions')}>本轮付款记录 <b>{newPayments.length} 笔 →</b></button><button onClick={()=>nav('payees')}>供应商名册 <b>{payees.length} 位 →</b></button></section></div><section className="payment-panel" aria-label="工作范围"><h2>{s.task_id===46?'按付款清单支付并回填回执':'审核本期账单并交付对账清单'}</h2><p>{w.brief}</p></section><div className="bank-cards">{w.accounts.map((a:any)=><button key={a.id} onClick={()=>nav('accounts')}><small>QINGHE · PROJECT ACCOUNT</small><h3>{a.name}</h3><span>•••• {a.number.slice(-4)}</span><strong>¥{money(d.balances[a.id])}</strong></button>)}</div></>}
    {page==='bills'&&<><PageHead title="账单中心" description="按批次与供应商编号核对。本期范围不包含历史账单和下期账单。"/><div className="payment-filters"><label>账单批次<select aria-label="账单批次" value={scope} onChange={e=>setScope(e.target.value)}><option value="current">本期 2026-10</option><option value="all">全部账单</option></select></label><input aria-label="搜索账单" placeholder="搜索账单编号或项目" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="payment-panel payment-table-wrap"><table className="payment-table"><thead><tr><th>账单 / 项目</th><th>供应商</th><th>应付金额</th><th>状态</th><th>操作</th></tr></thead><tbody>{w.bills.filter((b:any)=>(scope==='all'||w.batch_bills.includes(b.id))&&(!query||[b.id,b.project,b.purpose].some(x=>x.includes(query)))).map((b:any)=>{const p=d.objects[b.payee];return <tr key={b.id} data-bill={b.id}><td><b>{b.id}</b><small>{b.project} · {b.batch}</small></td><td>{p.name}<small>{p.record_code} · {p.company}</small></td><td>¥{money(b.cents)}</td><td>{values(w.transfers).some(t=>t.bill===b.id)?'已付款':'未付款'}<small>{w.bill_links[b.id]?'已关联 '+w.bill_links[b.id]:'未关联回执'}</small></td><td><button onClick={()=>openBill(b.id)}>查看账单</button></td></tr>;})}</tbody></table></div></>}
    {page==='bill'&&(bill?<BillDetail key={bill.id} api={api} bill={bill} prepare={()=>nav('transfer')} download={download}/>:<p role="alert">账单不存在</p>)}
    {page==='transfer'&&bill&&<TransferForm key={bill.id} api={api} bill={bill} done={id=>{setTransferId(id);nav('receipt');}}/>}
    {page==='payees'&&<><PageHead title="收款人名册" description="同名联系人可能属于不同供应商，请以供应商编号和完整账号确认身份。"/><input aria-label="搜索收款人" placeholder="搜索姓名、供应商编号或账号" value={query} onChange={e=>setQuery(e.target.value)}/><div className="payment-panel payment-table-wrap"><table className="payment-table"><thead><tr><th>供应商编号</th><th>收款人</th><th>完整账号</th><th>详情</th></tr></thead><tbody>{payees.filter((p:any)=>!query||[p.name,p.record_code,p.account].some(x=>x.includes(query))).map((p:any)=><tr data-payee={p.id} key={p.id}><td>{p.record_code}</td><td>{p.name}<small>{p.company}</small></td><td className="payment-account">{p.account}</td><td><button onClick={()=>{setPayeeId(p.id);nav('payee');}}>查看收款人</button></td></tr>)}</tbody></table></div></>}
    {page==='payee'&&(payee?<><PageHead title={payee.name} description={payee.record_code+' · '+payee.company}/><section className="payment-panel"><dl className="payment-facts"><dt>收款银行</dt><dd>{payee.bank}</dd><dt>完整收款账号</dt><dd className="payment-account">{payee.account}</dd><dt>供应商编号</dt><dd>{payee.record_code}</dd></dl><h2>关联账单</h2>{w.bills.filter((b:any)=>b.payee===payee.id).map((b:any)=><p key={b.id}><a href={api.applicationLink?.('bank',{bill:b.id})}>{b.id} · {b.purpose} · ¥{money(b.cents)}</a></p>)}</section></>:<p role="alert">收款人不存在</p>)}
    {page==='accounts'&&<><PageHead title="付款账户" description="本轮期初余额已包含历史交易；本轮付款会同步更新付款账户和收款账户余额。"/>{w.accounts.map((a:any)=><section className="payment-panel" data-account={a.id} key={a.id}><h2>{a.name}</h2><p className="payment-account">{a.number}</p><div className="payment-balances"><span>本轮期初<b>¥{money(w.opening_balances[a.id])}</b></span><span>本轮支出<b>¥{money(w.opening_balances[a.id]-d.balances[a.id])}</b></span><span>可用余额<b>¥{money(d.balances[a.id])}</b></span></div><h3>账户交易</h3>{values(w.transfers).filter(t=>t.payer===a.id).map(t=><p key={t.id}><a href={api.applicationLink?.('bank',{transfer:t.id})}>{t.id} · {t.bill} · 支出 ¥{money(t.cents)}</a></p>)}</section>)}</>}
    {page==='transactions'&&<><PageHead title="交易明细" description="付款确认后保存真实模拟流水和可下载回执；关联账单需单独核对回填。"/>{values(w.transfers).slice().reverse().map(t=><section className="payment-panel payment-transaction" data-transfer={t.id} key={t.id}><div><b>{d.objects[t.payee].name} · ¥{money(t.cents)}</b><p>{t.id} · {t.bill} · {t.occurred_at.replace('T',' ')}</p><small>{t.memo}</small></div><button onClick={()=>{setTransferId(t.id);nav('receipt');}}>查看付款回执</button></section>)}</>}
    {page==='receipt'&&(transfer?<><PageHead title={transfer.id+' · 付款成功'} description="款项已在模拟账户入账。请下载回执并回填对应账单。"/><section className="payment-panel"><div className="product-actions"><button onClick={()=>download('transfer-'+transfer.id)}>下载付款回执</button><a href={api.applicationLink?.('bank',{file:'transfer-'+transfer.id})}>打开付款文件</a><button onClick={()=>openBill(transfer.bill)}>回填对应账单</button></div><pre className="payment-document">{readFile(d.files['transfer-'+transfer.id])}</pre></section></>:<p role="alert">付款回执不存在</p>)}
    {page==='report'&&s.task_id===56&&<Reconciliation api={api} download={download}/>}
    {page==='file'&&(d.files[params.get('file')||'']?<section className="payment-panel"><PageHead title={d.files[params.get('file')!].name}/><pre className="payment-document">{readFile(d.files[params.get('file')!])}</pre></section>:<p role="alert">文件不存在</p>)}
  </main></Frame>;
}
