import {useState} from 'react';
import {Frame,PageHead,Notice,type ProductAPI} from './kit';
import './editorial.css';

export function Editorial({api}:{api:ProductAPI}) {
  const {s,d}=api,w=s.world;
  const queryId=new URLSearchParams(location.search).get('document')||'';
  const [page,setPage]=useState(queryId?'document':'home'),[active,setActive]=useState(queryId);
  const [scope,setScope]=useState(s.task_id===29?'weekly':w.scopes[0].id),[title,setTitle]=useState('');
  const [section,setSection]=useState(''),[article,setArticle]=useState(''),[summary,setSummary]=useState(''),[link,setLink]=useState('');
  const [directoryScope,setDirectoryScope]=useState(w.scopes[0].id),[directoryDoc,setDirectoryDoc]=useState(''),[directoryLink,setDirectoryLink]=useState(''),[count,setCount]=useState(0);
  const doc=w.documents[active];
  const command=(op:string,target:string,data:any={})=>api.mutate(op,target,JSON.stringify(data));
  const appLink=(app:string,params:Record<string,string>={})=>api.applicationLink!(app,params);
  function navigate(next:string){setPage(next);history.replaceState({},'',location.pathname)}
  function open(id:string,edit=false){setActive(id);setTitle(w.documents[id].title);setSection(Object.keys(w.documents[id].sections)[0]);setArticle('');setSummary('');setLink('');setPage(edit?'editor':'document');history.replaceState({},'',location.pathname+'?document='+encodeURIComponent(id))}
  function chooseArticle(id:string){setArticle(id);setLink(id?'news/articles/'+id:'');setSummary(id?d.objects[id].summary:'')}
  const articleHref=(value:string)=>/^news\/articles\/object-[a-f0-9]+$/.test(value)?appLink('news',{article:value.split('/').at(-1)!}):undefined;
  const docHref=(value:string)=>/^documents\/[a-z0-9-]+$/.test(value)?appLink('blog',{document:value.split('/').at(-1)!}):undefined;
  const rowCount=(document:any)=>Object.values(document.sections).reduce((total:number,section:any)=>total+section.rows.length,0);
  const saved=(document:any)=>document.saved?.title===document.title&&JSON.stringify(document.saved?.sections)===JSON.stringify(document.sections);
  const cards=(documents:any[])=> <div className="blog-cards">{documents.map((document:any,i:number)=><article className="blog-card" data-document={document.id} key={document.id}><div className={`blog-cover cover-${i%3}`}><span>FIELD NOTES</span><b>资料</b></div><div><small>{rowCount(document)} 篇引用 · {saved(document)?'已保存':'编辑中'}</small><button className="product-text-link" onClick={()=>open(document.id)}><h2>{document.title}</h2></button><p>{Object.values(document.sections).map((section:any)=>section.heading).join(' · ')}</p><button onClick={()=>open(document.id,true)}>编辑文档</button></div></article>)}</div>;
  const references=(document:any,editable=false)=><div className="editorial-document">{Object.entries(document.sections).map(([key,part]:any)=><section key={key} data-section={key}><h2>{part.heading}</h2>{part.rows.length?part.rows.map((row:any)=><article key={row.article} data-citation={row.article}><small>{d.objects[row.article]?.publisher} · {d.objects[row.article]?.record_code}</small><h3>{d.objects[row.article]?.name}</h3><p>{row.summary}</p>{articleHref(row.link)?<a href={articleHref(row.link)}>阅读原文 →</a>:<p role="alert">原文链接格式无效：{row.link}</p>}{editable&&<div className="editorial-row-actions"><button onClick={()=>{setSection(key);setArticle(row.article);setSummary(row.summary);setLink(row.link)}}>编辑引用 {d.objects[row.article]?.record_code}</button><button disabled={api.busy} onClick={()=>command('document.remove',document.id,{section:key,article:row.article})}>移除引用 {d.objects[row.article]?.record_code}</button></div>}</article>):<p className="editorial-empty">此章节还没有引用。</p>}</section>)}</div>;
  return <Frame brand="墨记" accent="#3e7153" page={page} navigate={navigate} tabs={[["home","工作台"],["documents","文档"],["reading","选定文章"],...(s.task_id===30?[["directory","资料目录"] as [string,string]]:[])]} tools={<a className="product-primary" href={appLink('news')}>浏览新闻 ↗</a>}>
    <main className="product-main editorial-workspace"><Notice api={api}/>
      <section className="editorial-brief" aria-label="工作范围"><strong>{s.execution.assignment}</strong><details><summary>查看整理要求与交付说明</summary><p>{w.brief}</p></details></section>
      {page==='home'&&<><PageHead eyebrow="YOUR WRITING DESK" title="把资料，整理成清晰的阅读线索。" description="汇编原文、整理摘要，与团队共享有据可查的文档。"/><section className="blog-welcome"><div><span className="product-eyebrow">编辑计划</span><h2>{s.task_id===29?w.report_title:'项目阅读资料'}</h2><p>{w.scopes.map((scope:any)=>scope.name).join(' · ')}</p><button className="product-primary" onClick={()=>navigate('documents')}>管理文档</button><a href={appLink('news')}>到新闻资料库选稿 →</a></div></section>{cards(Object.values(w.documents))}</>}
      {page==='documents'&&<><PageHead title="文档" description="创建简报或项目资料页，添加引用后保存。"/><form className="editorial-create" onSubmit={async e=>{e.preventDefault();if(await command('document.create','',{scope,title}))setTitle('')}}><label>文档范围<select aria-label="文档范围" value={scope} onChange={e=>setScope(e.target.value)}>{s.task_id===29?<option value="weekly">本周四个专题</option>:w.scopes.map((scope:any)=><option value={scope.id} key={scope.id}>{scope.name}</option>)}</select></label><label className="editorial-grow">文档标题<input aria-label="文档标题" required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="product-primary" disabled={api.busy}>创建文档</button></form>{cards(Object.values(w.documents))}</>}
      {page==='reading'&&<><PageHead title="选定文章" description="在新闻资料库中维护选稿，再为文档添加引用。"/>{w.scopes.map((scope:any)=><section className="editorial-reading" key={scope.id}><h2>{scope.name} · {w.selections[scope.id].length} 篇</h2>{w.selections[scope.id].map((id:string)=><article key={id}><small>{d.objects[id].publisher} · {d.objects[id].record_code}</small><h3>{d.objects[id].name}</h3><p>{d.objects[id].summary}</p><a href={appLink('news',{article:id})}>阅读原文 →</a></article>)}</section>)}</>}
      {(page==='document'||page==='editor')&&(!doc?<p role="alert">文档不存在，请返回文档列表。</p>:<><PageHead title={doc.title} description={`${rowCount(doc)} 篇引用 · ${saved(doc)?'全部更改已保存':'有未保存的更改'}`}/><div className="editorial-toolbar"><button onClick={()=>navigate('documents')}>返回文档列表</button>{page==='document'?<button className="product-primary" onClick={()=>open(active,true)}>编辑此文档</button>:<><button onClick={()=>open(active)}>预览文档</button><button className="product-primary" disabled={api.busy} onClick={()=>command('document.save',active)}>保存文档</button></>}</div>
        {page==='editor'&&<><form className="editorial-create" onSubmit={e=>{e.preventDefault();void command('document.title',active,{title})}}><label className="editorial-grow">文档标题<input aria-label="文档标题" maxLength={160} required value={title} onChange={e=>setTitle(e.target.value)}/></label><button disabled={api.busy}>更新标题</button></form><form className="editorial-citation-form" onSubmit={async e=>{e.preventDefault();if(await command('document.article',active,{section,article,link,summary})){setArticle('');setLink('');setSummary('')}}}><h2>添加或编辑引用</h2><div className="editorial-toolbar"><label>章节<select aria-label="章节" value={section} onChange={e=>{setSection(e.target.value);chooseArticle('')}}>{Object.entries(doc.sections).map(([key,part]:any)=><option key={key} value={key}>{part.heading}</option>)}</select></label><label className="editorial-grow">引用文章<select aria-label="引用文章" required value={article} onChange={e=>chooseArticle(e.target.value)}><option value="">从选定文章中选择</option>{(w.selections[section]||[]).map((id:string)=><option value={id} key={id}>{d.objects[id].name} · {d.objects[id].record_code}</option>)}</select></label></div><label>原文链接<input aria-label="原文链接" required value={link} onChange={e=>setLink(e.target.value)}/></label><label>引用摘要<textarea aria-label="引用摘要" required rows={4} value={summary} onChange={e=>setSummary(e.target.value)}/></label><button disabled={api.busy||!article} className="product-primary">保存引用</button></form></>}
        {references(doc,page==='editor')}{page==='editor'&&<details className="editorial-manage"><summary>文档管理</summary><button disabled={api.busy} onClick={async()=>{if(confirm('删除此文档？')&&await command('document.delete',active))navigate('documents')}}>删除文档</button></details>}
      </>)}
      {page==='directory'&&<><PageHead title="项目资料目录" description="为每个项目登记可打开的资料页与实际文章数。"/><form className="editorial-citation-form" onSubmit={e=>{e.preventDefault();void command('directory.entry',directoryScope,{document:directoryDoc,link:directoryLink,count})}}><div className="editorial-toolbar"><label>项目<select aria-label="目录项目" value={directoryScope} onChange={e=>setDirectoryScope(e.target.value)}>{w.scopes.map((scope:any)=><option value={scope.id} key={scope.id}>{scope.name}</option>)}</select></label><label className="editorial-grow">资料页<select aria-label="目录资料页" required value={directoryDoc} onChange={e=>{setDirectoryDoc(e.target.value);setDirectoryLink(e.target.value?'documents/'+e.target.value:'');setCount(e.target.value?rowCount(w.documents[e.target.value]):0)}}><option value="">请选择文档</option>{Object.values(w.documents).map((doc:any)=><option key={doc.id} value={doc.id}>{doc.title}</option>)}</select></label><label>文章数<input aria-label="目录文章数" type="number" min={0} value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div><label>资料页链接<input aria-label="资料页链接" required value={directoryLink} onChange={e=>setDirectoryLink(e.target.value)}/></label><button className="product-primary" disabled={api.busy||!directoryDoc}>保存目录条目</button></form><div className="editorial-directory">{Object.entries(w.directory).map(([key,entry]:any)=><article key={key} data-directory={key}><div><h2>{w.scopes.find((scope:any)=>scope.id===key)?.name}</h2><p>{entry.count} 篇文章</p>{docHref(entry.link)?<a href={docHref(entry.link)}>打开资料页 →</a>:<p role="alert">资料页链接无效</p>}</div><button disabled={api.busy} onClick={()=>command('directory.remove',key)}>移除目录条目</button></article>)}</div></>}
    </main>
  </Frame>;
}
