import {useState} from 'react';
import {Frame,PageHead,Notice,type ProductAPI} from './kit';
import './publishing.css';

export function Publishing({api}:{api:ProductAPI}) {
  const {s,d}=api,w=s.world;
  const initialPost=new URLSearchParams(location.search).get('post')||'';
  const [page,setPage]=useState(initialPost?'article':'home'),[active,setActive]=useState(''),[postId,setPostId]=useState(initialPost);
  const [project,setProject]=useState(''),[batch,setBatch]=useState('2026-W06'),[query,setQuery]=useState('');
  const [column,setColumn]=useState(''),[cover,setCover]=useState(''),[summary,setSummary]=useState(''),[publishAt,setPublishAt]=useState('');
  const [indexColumn,setIndexColumn]=useState(w.columns[0].id),[indexPost,setIndexPost]=useState(''),[recipient,setRecipient]=useState('');
  const command=(op:string,target:string,data:any={})=>api.mutate(op,target,JSON.stringify(data));
  const link=(app:string,params:Record<string,string>={})=>api.applicationLink!(app,params);
  const author=(id:number)=>w.authors.find((a:any)=>a.id===id);
  const columnName=(id:string)=>w.columns.find((c:any)=>c.id===id)?.name;
  const coverItem=(id:string)=>w.covers.find((c:any)=>c.id===id);
  const publication=(id:string)=>Object.values(w.publications).find((p:any)=>p.draft===id) as any;
  function navigate(next:string){setPage(next);history.replaceState({},'',location.pathname)}
  function edit(id:string){
    const item=d.objects[id],meta=w.edits[id]||{column:'',cover:item.default_cover,summary:item.summary,publish_at:''};
    setActive(id);setColumn(meta.column);setCover(meta.cover);setSummary(meta.summary);setPublishAt(meta.publish_at);setRecipient('');navigate('editor');
  }
  function drafts(id:string){setProject(id);setBatch('2026-W06');navigate('drafts')}
  function openPost(id:string){setPostId(id);setRecipient('');setPage('article');history.replaceState({},'',location.pathname+'?post='+encodeURIComponent(id))}
  const current=d.objects[active],posted=current?publication(active):undefined,article=w.publications[postId];
  const fieldsSaved=!!w.edits[active]&&w.edits[active].column===column&&w.edits[active].cover===cover&&w.edits[active].summary===summary&&w.edits[active].publish_at===publishAt;
  const rows=s.items.filter((item:any)=>(!project||item.project===project)&&(!batch||item.batch===batch)&&item.name.includes(query));
  const cards=(items:any[])=><div className="blog-cards">{items.map((item:any)=><article className="blog-card" key={item.id} data-draft={item.id}><div className="publishing-card-cover"><img src={coverItem(item.default_cover).url} alt={coverItem(item.default_cover).name}/><span>{publication(item.id)?'已发布':'草稿'}</span></div><div><small>{item.record_code} · {item.project_name} · {item.batch}</small><button className="product-text-link" onClick={()=>edit(item.id)}><h2>{item.name}</h2></button><p>{item.summary}</p><small>作者 {author(item.author)?.name} · 更新于 {item.updated_at.slice(0,16).replace('T',' ')}<br/>正文 {Array.from(item.text).length} 字 · {item.tags.length} 个标签</small><div className="publishing-tags">{item.tags.map((tag:string)=><span key={tag}>{tag}</span>)}</div><button onClick={()=>edit(item.id)}>编辑发布</button>{publication(item.id)&&<button onClick={()=>openPost(publication(item.id).id)}>查看文章</button>}</div></article>)}</div>;
  const postHref=(post:any)=>link('blog',{post:post.id});
  return <Frame brand="墨记" accent="#3e7153" page={page} navigate={navigate} tabs={[["home","工作台"],["plan","编辑排期"],["drafts","我的草稿"],["published","已发布"],["index","栏目索引"],...(s.task_id===42?[["notices","作者通知"] as [string,string]]:[])]} tools={s.task_id===42?<a className="product-primary" href={link('im')}>团队消息 ↗</a>:undefined}>
    <main className="product-main publishing-workspace"><Notice api={api}/>
      <section className="publishing-brief" aria-label="工作范围"><strong>{s.execution.assignment}</strong><details><summary>查看发布要求与交付说明</summary><p>{w.brief}</p></details></section>
      {page==='home'&&<><PageHead eyebrow="YOUR WRITING DESK" title="让值得分享的内容，抵达读者。" description="从草稿与排期开始，管理每篇文章的发布和归档。"/><section className="blog-welcome"><div><span className="product-eyebrow">本周编辑计划</span><h2>三个栏目的内容准备</h2><p>{w.projects.map((p:any)=>p.name).join(' · ')}</p><button className="product-primary" onClick={()=>navigate('plan')}>查看编辑排期</button></div><div className="blog-paper">Publish<br/><span>stories / people / ideas</span></div></section><div className="product-section"><h2>本期草稿</h2><button onClick={()=>drafts('')}>查看全部 →</button></div>{cards(s.items.filter((x:any)=>x.batch==='2026-W06').slice(0,3))}</>}
      {page==='plan'&&<><PageHead title="编辑排期" description="仅处理本期计划列出的稿件。发布时间均为北京时间。"/>{w.projects.map((p:any)=><section className="publishing-plan" key={p.id} data-project={p.id}><div className="publishing-toolbar"><div className="publishing-grow"><h2>{p.name}</h2><p>批次 {p.batch} · {p.candidates.length} 篇候选稿件</p></div><button onClick={()=>drafts(p.id)}>查看本期草稿</button></div>{s.task_id===40?<div className="publishing-plan-meta"><img src={coverItem(p.cover).url} alt={coverItem(p.cover).name}/><div><p>发布栏目：{columnName(p.column)}</p><p>指定封面：{coverItem(p.cover).name}</p><p>发布摘要：{p.summary}</p><p>发布时间：{p.publish_at.replace('T',' ')}</p></div></div>:<div className="publishing-plan-table"><table><thead><tr><th>稿件 / 作者</th><th>标签</th><th>发布栏目</th><th>发布时间</th><th/></tr></thead><tbody>{w.plan.filter((plan:any)=>plan.project===p.id).map((plan:any)=>{const item=d.objects[plan.draft];return <tr key={item.id} data-plan-draft={item.id}><td><strong>{item.name}</strong><small>{item.record_code} · {author(item.author)?.name}</small></td><td>{item.tags.length} 个<br/>{item.tags.join(' · ')||'无标签'}</td><td>{columnName(plan.column)}</td><td>{plan.publish_at.replace('T',' ')}</td><td><button onClick={()=>edit(item.id)}>打开稿件</button></td></tr>})}</tbody></table></div>}</section>)}</>}
      {page==='drafts'&&<><PageHead title="我的草稿" description="更新时间与字数来自最初的草稿快照，正文长度不包含标题。"/><div className="publishing-toolbar"><label>编辑计划<select aria-label="编辑计划" value={project} onChange={e=>setProject(e.target.value)}><option value="">全部计划</option>{w.projects.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="personal">个人随笔</option></select></label><label>批次<select aria-label="稿件批次" value={batch} onChange={e=>setBatch(e.target.value)}><option value="2026-W06">本期 2026-W06</option><option value="2026-W05">上期 2026-W05</option><option value="">全部批次</option></select></label><label className="publishing-grow">搜索稿件<input aria-label="搜索稿件" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{cards(rows)}</>}
      {page==='editor'&&current&&<><PageHead title={current.name} description={`${current.record_code} · ${current.project_name} · 作者 ${author(current.author)?.name}`} action={<button onClick={()=>navigate('plan')}>查看排期</button>}/><section className="blog-editor"><span className="product-eyebrow">DRAFT SNAPSHOT</span><p>更新于 {current.updated_at.slice(0,16).replace('T',' ')} · 正文 {Array.from(current.text).length} 字</p><div className="blog-editor-body">{current.text}</div><div className="publishing-tags">{current.tags.map((tag:string)=><span key={tag}>{tag}</span>)}<small>{current.tags.length} 个标签</small></div></section><form className="publishing-form" onSubmit={e=>{e.preventDefault();void command('post.metadata',active,{column,cover,summary,publish_at:publishAt})}}><h2>发布资料</h2><div className="publishing-toolbar"><label>发布栏目<select aria-label="发布栏目" required disabled={!!posted} value={column} onChange={e=>setColumn(e.target.value)}><option value="">请选择栏目</option>{w.columns.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="publishing-grow">封面<select aria-label="发布封面" required disabled={!!posted} value={cover} onChange={e=>setCover(e.target.value)}>{w.covers.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>发布时间（北京时间）<input aria-label="发布时间" type="datetime-local" required disabled={!!posted} value={publishAt} onChange={e=>setPublishAt(e.target.value)}/></label></div>{cover&&<img className="publishing-cover-preview" src={coverItem(cover).url} alt={coverItem(cover).name}/>}<label>发布摘要<textarea aria-label="发布摘要" rows={3} required maxLength={500} disabled={!!posted} value={summary} onChange={e=>setSummary(e.target.value)}/></label><div className="publishing-toolbar"><button disabled={api.busy||!!posted}>保存发布资料</button><button type="button" className="product-primary" disabled={api.busy||!!posted||!fieldsSaved} onClick={()=>command('post.publish',active)}>{posted?'已发布':'发布文章'}</button>{posted&&<a href={postHref(posted)}>打开已发布文章 →</a>}</div><p>{posted?'文章已发布。':fieldsSaved?'发布资料已保存，可以发布文章。':'请先保存完整的发布资料；修改字段后需要再次保存。'}</p></form></>}
      {page==='published'&&<><PageHead title="已发布文章" description={`${Object.keys(w.publications).length} 篇文章`}/><div className="blog-cards">{Object.values(w.publications).map((post:any)=><article className="blog-card" data-publication={post.id} key={post.id}><div className="publishing-card-cover"><img src={coverItem(post.cover).url} alt={coverItem(post.cover).name}/></div><div><small>{columnName(post.column)} · {post.publish_at.replace('T',' ')}</small><h2>{post.title}</h2><p>{post.summary}</p><button onClick={()=>openPost(post.id)}>打开文章</button></div></article>)}</div></>}
      {page==='article'&&(!article?<p role="alert">文章不存在或已撤下。</p>:<><div className="publishing-toolbar"><button onClick={()=>navigate('published')}>返回已发布文章</button><button onClick={()=>navigate('index')}>管理栏目索引</button><button disabled={api.busy} onClick={async()=>{if(await command('post.withdraw',article.id))navigate('published')}}>撤下文章</button></div><article className="publication-body" data-publication={article.id}><img src={coverItem(article.cover).url} alt={coverItem(article.cover).name}/><div><span className="product-eyebrow">{columnName(article.column)}</span><h1>{article.title}</h1><p className="publication-meta">{author(article.author)?.name} · {article.publish_at.replace('T',' ')} 北京时间</p><p className="publication-summary">{article.summary}</p><div className="publication-text">{article.body}</div></div></article>{s.task_id===42&&<section className="publishing-form"><h2>通知作者</h2><p>将这篇文章的实际发布链接和摘要发送到作者的私聊。</p><div className="publishing-toolbar"><label className="publishing-grow">通知收件人<select aria-label="通知收件人" value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">请选择联系人</option>{w.authors.map((a:any)=><option value={a.id} key={a.id}>{a.name} · {a.account}</option>)}</select></label><button className="product-primary" disabled={api.busy||!recipient} onClick={()=>command('post.notify',article.id,{recipient:Number(recipient)})}>发送发布通知</button><a href={link('im')}>打开团队消息 →</a></div>{w.notifications.filter((n:any)=>n.publication===article.id).map((n:any)=><div className="publishing-notice" key={n.id} data-notice={n.id}><span>已发送至 {author(n.recipient)?.name}</span><button disabled={api.busy} onClick={()=>command('notice.withdraw',n.id)}>撤回通知</button></div>)}</section>}</>)}
      {page==='index'&&<><PageHead title="栏目索引" description="将已发布的文章归入栏目，读者可从索引直接打开正文。"/><form className="publishing-form" onSubmit={e=>{e.preventDefault();void command('index.add',indexColumn,{publication:indexPost})}}><div className="publishing-toolbar"><label>索引栏目<select aria-label="索引栏目" value={indexColumn} onChange={e=>setIndexColumn(e.target.value)}>{w.columns.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="publishing-grow">已发布文章<select aria-label="索引文章" required value={indexPost} onChange={e=>setIndexPost(e.target.value)}><option value="">请选择文章</option>{Object.values(w.publications).map((post:any)=><option key={post.id} value={post.id}>{post.title} · {d.objects[post.draft].record_code}</option>)}</select></label><button className="product-primary" disabled={api.busy||!indexPost}>加入栏目索引</button></div></form>{w.columns.map((c:any)=><section className="publishing-index" data-index={c.id} key={c.id}><h2>{c.name}</h2>{(w.index[c.id]||[]).map((entry:any)=>{const post=w.publications[entry.publication];return <article key={post.id} data-index-post={post.id}><div><a href={postHref(post)}>{post.title}</a><p>{post.publish_at.replace('T',' ')} · {post.summary}</p></div><button disabled={api.busy} onClick={()=>command('index.remove',c.id,{publication:post.id})}>移出索引</button></article>})}{!(w.index[c.id]||[]).length&&<p>此栏目尚未收录文章。</p>}</section>)}</>}
      {page==='notices'&&<><PageHead title="作者通知" description="发布链接与接收人可以在这里核对。"/><a href={link('im')}>打开团队消息 →</a>{w.notifications.map((notice:any)=><article className="publishing-notice publishing-form" data-notice={notice.id} key={notice.id}><div><h2>{notice.title}</h2><p>收件人：{author(notice.recipient)?.name}</p><a href={postHref(w.publications[notice.publication])}>打开已发布文章 →</a></div><button disabled={api.busy} onClick={()=>command('notice.withdraw',notice.id)}>撤回通知</button></article>)}</>}
    </main>
  </Frame>;
}
