import {useState} from 'react';
import {Frame,PageHead,Notice,minutes,type ProductAPI} from './kit';

export function Screening({api}:{api:ProductAPI}) {
  const {s,d}=api,w=s.world,event=w.event,q=w.queue;
  const search=new URLSearchParams(location.search);
  const [page,setPage]=useState(search.has('video')?'player':search.has('file')?'file':'home');
  const [active,setActive]=useState(search.get('video')||'');
  const [folder,setFolder]=useState(w.folders[0].id);
  const [query,setQuery]=useState('');
  const [name,setName]=useState(q.name);
  const [error,setError]=useState('');
  const command=(op:string,target='',data={},ids:string[]=[])=>api.mutate(op,target,JSON.stringify(data),ids);
  const item=(id:string)=>d.objects[id];
  const identity=(id:string)=>`${item(id).record_code} · ${item(id).name}`;
  const saved=q.saved?.name===q.name&&JSON.stringify(q.saved?.members)===JSON.stringify(q.members);
  const fresh=w.schedule&&saved&&w.schedule.name===q.name&&JSON.stringify(w.schedule.members)===JSON.stringify(q.members)&&JSON.stringify(w.schedule.timing)===JSON.stringify(w.timing);
  function nav(next:string){setPage(next);if(next!=='library')setQuery('');setError('');api.clearNotice?.();}
  function play(id:string){setActive(id);nav('player');}
  async function download(){try {await api.downloadFile?.('screening-timetable',d.files['screening-timetable'].name);}catch(e){setError(String(e));}}
  function changePosition(id:string,to:number){const ids=q.members.filter((x:string)=>x!==id);ids.splice(Math.max(0,Math.min(ids.length,to)),0,id);return command('queue.order','',{},ids);}
  function QueueItem({id,index}:{id:string;index:number}) {
    const [replacement,setReplacement]=useState(''),[position,setPosition]=useState(String(index+1));
    const video=item(id);
    return <article data-queue-video={id} className="screening-queue-row"><span className="screening-number">{String(index+1).padStart(2,'0')}</span><button className="screening-poster" onClick={()=>play(id)} aria-label={'播放 '+video.name}><img src={`/native-assets/media/poster-${video.asset_index}.jpg`} alt={video.name}/></button><div className="screening-queue-info"><h3>{video.name}</h3><p>{video.record_code} · {minutes(video.duration)} · {video.category} 类 · {video.edition}</p><div className="screening-row-controls"><button aria-label={'上移 '+video.name} disabled={api.busy||index===0} onClick={()=>changePosition(id,index-1)}>↑</button><button aria-label={'下移 '+video.name} disabled={api.busy||index===q.members.length-1} onClick={()=>changePosition(id,index+1)}>↓</button><label>位置<input aria-label={'位置 '+video.record_code} type="number" min={1} max={q.members.length} value={position} onChange={e=>setPosition(e.target.value)}/></label><button disabled={api.busy||!Number.isInteger(Number(position))||Number(position)<1||Number(position)>q.members.length} onClick={()=>changePosition(id,Number(position)-1)}>移动</button><button disabled={api.busy} onClick={()=>command('queue.remove',id)}>移出队列</button></div><div className="screening-row-controls"><select aria-label={'替换影片 '+video.record_code} value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">选择替换版本</option>{s.items.filter((r:any)=>!q.members.includes(r.id)).map((r:any)=><option key={r.id} value={r.id}>{identity(r.id)}</option>)}</select><button disabled={api.busy||!replacement} onClick={()=>command('queue.replace',id,{replacement})}>替换影片</button></div></div></article>;
  }
  function TimingEditor(){
    const [starts,setStarts]=useState(w.timing.starts_at.slice(0,16)),[gap,setGap]=useState(String(w.timing.turnaround_seconds));
    const [breaks,setBreaks]=useState<Record<string,number>>({...w.timing.breaks});
    const [after,setAfter]=useState(''),[seconds,setSeconds]=useState('300');
    const dirty=starts!==w.timing.starts_at.slice(0,16)||Number(gap)!==w.timing.turnaround_seconds||Object.keys(breaks).length!==Object.keys(w.timing.breaks).length||Object.entries(breaks).some(([id,n])=>w.timing.breaks[id]!==n);
    return <section className="screening-panel"><h2>放映时间设置</h2><div className="screening-timing-fields"><label>开场时间（北京时间）<input aria-label="开场时间" type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/></label><label>两片之间换片秒数<input aria-label="换片秒数" type="number" min="0" max="600" value={gap} onChange={e=>setGap(e.target.value)}/></label></div><p>最后一部影片后不加换片时间。休息安排在指定影片结束后，额外计入总时长。</p><h3>休息安排</h3>{Object.entries(breaks).map(([id,n])=><div className="screening-row-controls" data-break={id} key={id}><span>{identity(id)} 后休息 {n} 秒</span><button onClick={()=>setBreaks(old=>{const next={...old};delete next[id];return next;})}>移除休息</button></div>)}<div className="screening-row-controls"><label>休息位置<select aria-label="休息位置" value={after} onChange={e=>setAfter(e.target.value)}><option value="">选择一部影片之后</option>{q.members.map((id:string)=><option key={id} value={id}>{identity(id)}</option>)}</select></label><label>休息秒数<input aria-label="休息秒数" type="number" min="1" max="3600" value={seconds} onChange={e=>setSeconds(e.target.value)}/></label><button disabled={!after||Number(seconds)<=0} onClick={()=>{setBreaks(old=>({...old,[after]:Number(seconds)}));setAfter('');}}>添加休息</button></div><button className="product-primary" disabled={api.busy||!starts} onClick={()=>command('timing.save','',{starts_at:starts+':00+08:00',turnaround_seconds:Number(gap),breaks})}>保存时间设置</button><button className="product-primary" disabled={api.busy||!saved||!w.timing.starts_at||dirty} onClick={()=>command('schedule.save')}>生成并保存时间表</button>{dirty&&<p role="status">有未保存的时间设置，请先保存再生成时间表。</p>}</section>;
  }
  const list=page==='folder'?w.folders.find((f:any)=>f.id===folder).members.map(item):s.items.map((r:any)=>item(r.id));
  const current=item(active),position=q.members.indexOf(active);
  return <Frame brand="映像放映室" accent="#ae583d" page={page} navigate={nav} tabs={[["home","发现"],["plan","活动计划"],["folders","收藏夹"],["library","视频资料库"],["queue","播放队列"],["schedule","放映时间表"]]} tools={<input aria-label="搜索影片" placeholder="搜索影片名称或编号" value={query} onChange={e=>{setQuery(e.target.value);nav('library');}}/>}>
    <main className="product-main screening-workspace"><Notice api={api}/>{error&&<p role="alert">{error}</p>}
      {page==='home'&&<><section className="media-hero"><img src="/native-assets/media/poster-0.jpg" alt="开放电影森林剧照"/><div><span>COMMUNITY SCREENING</span><h1>一起走进有故事的森林。</h1><p>社区开放电影之夜 · 片单与放映安排</p><button onClick={()=>nav('plan')}>查看活动计划 →</button></div></section><section className="screening-panel" aria-label="工作范围"><h2>{event.title}</h2><p>{s.execution.assignment}</p><p>{w.brief}</p></section><div className="screening-folder-grid">{w.folders.map((f:any)=><button key={f.id} onClick={()=>{setFolder(f.id);nav('folder');}}><span>▤</span><h3>{f.name}</h3><p>{f.members.length} 部影片</p></button>)}</div></>}
      {page==='plan'&&<><PageHead title={event.title} description="活动单 · 北京时间 · 所有排期以本单为准"/><section className="screening-panel"><h2>放映与交付要求</h2><p>{w.brief}</p><dl className="screening-event"><dt>保存队列名称</dt><dd>{event.title}</dd><dt>开场</dt><dd>{event.starts_at.replace('T',' ').replace('+08:00','')} 北京时间</dd><dt>换片</dt><dd>相邻影片之间 {event.turnaround_seconds} 秒</dd><dt>来源顺序</dt><dd>{w.folders.map((f:any)=>f.name).join(' → ')}</dd></dl><h3>排除项</h3><ul>{event.exclude.map((r:any)=><li key={r.video}>{identity(r.video)}：{r.reason}</li>)}</ul><h3>换片要求</h3>{event.replacements.map((r:any)=><p key={r.old} data-replacement={r.old}><b>{identity(r.old)}</b> → <b>{identity(r.new)}</b><br/>{r.reason} 替换版占原片在汇总清单中的位置。</p>)}<h3>休息安排</h3><ul>{event.breaks.map((r:any)=><li key={r.after}>{identity(r.after)} 之后休息 {r.seconds} 秒 · {r.reason}</li>)}</ul><button onClick={()=>nav('folders')}>打开来源收藏夹</button></section></>}
      {page==='folders'&&<><PageHead title="活动收藏夹" description="按活动单顺序汇总；相同影片编号只保留首次出现。"/><div className="screening-folder-grid">{w.folders.map((f:any,i:number)=><article className="screening-panel" data-folder={f.id} key={f.id}><span className="product-eyebrow">来源 {i+1}</span><h2>{f.name}</h2><p>{f.members.length} 部影片</p><button onClick={()=>{setFolder(f.id);nav('folder');}}>查看片单</button><button disabled={api.busy} onClick={()=>command('queue.import',f.id)}>汇入播放队列</button></article>)}</div></>}
      {(page==='folder'||page==='library')&&<><PageHead title={page==='folder'?w.folders.find((f:any)=>f.id===folder).name:'视频资料库'} description="影片编号区分版本 · 分类与时长见各影片资料" action={page==='folder'?<button disabled={api.busy} onClick={()=>command('queue.import',folder)}>汇入播放队列</button>:undefined}/><div className="media-grid">{list.filter((r:any)=>(r.name+' '+r.record_code).includes(query)).map((r:any)=><article data-video={r.id} key={r.id}><button className="media-thumbnail" onClick={()=>play(r.id)}><img src={`/native-assets/media/poster-${r.asset_index}.jpg`} alt={r.name}/><span>▶</span><small>{minutes(r.duration)}</small></button><div><h3>{r.name}</h3><p>{r.record_code} · {r.edition}</p><p>{r.category} 类 · {minutes(r.duration)} · {r.duration<event.short_below_seconds?'短片':'长片'}</p><button disabled={api.busy||q.members.includes(r.id)} onClick={()=>command('queue.add',r.id)}>{q.members.includes(r.id)?'已在队列':'加入队列'}</button></div></article>)}</div></>}
      {page==='queue'&&<><PageHead title="播放队列" description={`${q.members.length} 部影片 · 片长合计 ${minutes(q.members.reduce((sum:number,id:string)=>sum+item(id).duration,0))}（不含换片与休息）`} action={<button onClick={()=>nav('folders')}>添加来源影片</button>}/><section className="screening-panel"><label>队列名称<input aria-label="队列名称" value={name} onChange={e=>setName(e.target.value)}/></label><div className="screening-row-controls"><button disabled={api.busy||!name.trim()} onClick={()=>command('queue.name','',{name})}>保存名称</button><button className="product-primary" disabled={api.busy||!q.name||!q.members.length||name!==q.name} onClick={()=>command('queue.save')}>保存播放队列</button><span role="status">{saved?'播放队列已保存':'播放队列尚有未保存的变更'}</span>{q.members.length>0&&<button onClick={()=>play(q.members[0])}>从头播放队列</button>}<button onClick={()=>nav('schedule')}>编排放映时间</button></div></section>{q.members.map((id:string,index:number)=><QueueItem key={id+'-'+index} id={id} index={index}/>)}{!q.members.length&&<p>从收藏夹汇入影片，或在资料库中逐部添加。</p>}</>}
      {page==='player'&&current&&<><button className="product-back" onClick={()=>nav('queue')}>← 返回播放队列</button><video key={current.id} className="media-player" controls autoPlay playsInline src={api.mediaUrl?.(current.id)} poster={`/native-assets/media/poster-${current.asset_index}.jpg`} onEnded={()=>{if(position>=0&&position+1<q.members.length)setActive(q.members[position+1]);}}/><PageHead title={current.name} description={`${current.record_code} · ${minutes(current.duration)} · ${current.category} 类`}/><p>{current.text}</p><div className="screening-row-controls"><button disabled={position<=0} onClick={()=>setActive(q.members[position-1])}>上一部</button><span>{position>=0?`队列 ${position+1} / ${q.members.length}`:'资料库预览'}</span><button disabled={position<0||position===q.members.length-1} onClick={()=>setActive(q.members[position+1])}>下一部</button></div><footer className="media-credit">Big Buck Bunny © 2008 Blender Foundation · CC BY 3.0 · 片段与循环剪辑</footer></>}
      {page==='schedule'&&<><PageHead title="放映时间表" description="按保存的队列、真实片长、换片时间和休息安排计算。"/><TimingEditor/><div className="screening-row-controls"><span role="status">{fresh?'时间表与当前队列一致':'请在最终队列及时间设置保存后，生成时间表。'}</span></div>{w.schedule&&<section className="screening-panel"><h2>{w.schedule.name}</h2>{!fresh&&<p className="screening-stale" role="alert">队列或时间设置已变化，下表是已保存版本，需要重新生成。</p>}<div className="screening-table-wrap"><table className="product-table"><thead><tr><th>序号</th><th>影片</th><th>开始</th><th>结束</th><th>换片秒</th><th>休息秒</th></tr></thead><tbody>{w.schedule.rows.map((r:any,i:number)=><tr key={r.video} data-schedule-video={r.video}><td>{i+1}</td><td><button className="product-text-link" onClick={()=>play(r.video)}>{r.record_code} · {r.name}</button></td><td>{r.starts_at.slice(11,19)}</td><td>{r.ends_at.slice(11,19)}</td><td>{r.turnaround_seconds}</td><td>{r.break_seconds}</td></tr>)}</tbody></table></div><p>活动结束：{w.schedule.ends_at.replace('T',' ')} · 北京时间</p><div className="screening-row-controls"><button onClick={()=>download()}>下载 CSV 时间表</button><a href={api.applicationLink?.('media',{file:'screening-timetable'})}>打开时间表文件</a></div></section>}</>}
      {page==='file'&&d.files['screening-timetable']&&<section className="screening-panel"><PageHead title={d.files['screening-timetable'].name} action={<button onClick={()=>download()}>下载 CSV 时间表</button>}/><pre className="screening-file">{new TextDecoder().decode(Uint8Array.from(atob(d.files['screening-timetable'].content),(c)=>c.charCodeAt(0)))}</pre></section>}
    </main>
  </Frame>;
}
