import {useState} from 'react';
import {Frame,PageHead,Notice,type ProductAPI} from './kit';
import {ProductArt} from './Shop';

const values=(x:any):any[]=>Object.values(x);
const readFile=(file:any)=>file?new TextDecoder().decode(Uint8Array.from(atob(file.content),(c)=>c.charCodeAt(0))):'';
const send=(api:ProductAPI,op:string,target='',data={})=>api.mutate(op,target,JSON.stringify(data));
const currentRows=(w:any,r:any)=>r.products.map((sku:string)=>({sku,cart_quantity:w.cart[sku]||0,favorite:w.favorites.includes(sku)}));
const signature=(rows:any[])=>JSON.stringify(rows.map(r=>[r.sku,r.cart_quantity,r.favorite]));

function ProductDetail({api,item}:{api:ProductAPI,item:any}) {
  const w=api.s.world,[quantity,setQuantity]=useState(w.cart[item.id]||1);
  return <div className="shop-detail"><ProductArt item={item} index={0}/><section><span className="product-eyebrow">{item.record_code} · {item.vendor}</span><h1>{item.name}</h1><p>{item.spec}</p><p>{item.text}</p><div className="purchase-tags">{item.tags.map((tag:string)=><span key={tag}>{tag}</span>)}</div><dl className="purchase-facts"><dt>单价</dt><dd>¥{item.price}</dd><dt>评分</dt><dd>{item.rating.toFixed(1)}</dd><dt>初始库存</dt><dd>{item.stock} 件</dd><dt>当前库存</dt><dd>{w.stock[item.id]} 件</dd><dt>购物车</dt><dd>{w.cart[item.id]||0} 件</dd><dt>收藏状态</dt><dd>{w.favorites.includes(item.id)?'已收藏':'未收藏'}</dd></dl><label>购买数量<input aria-label="购买数量" type="number" min="1" max={w.stock[item.id]} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><div className="product-actions"><button className="product-primary" disabled={api.busy} onClick={()=>send(api,'cart.set',item.id,{quantity})}>{w.cart[item.id]?'更新购物车数量':'加入购物车'}</button><button disabled={api.busy||!w.cart[item.id]} onClick={()=>send(api,'cart.remove',item.id)}>移出购物车</button><button disabled={api.busy} onClick={()=>send(api,w.favorites.includes(item.id)?'favorite.remove':'favorite.add',item.id)}>{w.favorites.includes(item.id)?'取消收藏':'收藏商品'}</button></div></section></div>;
}

function Checkout({api,selected,done}:{api:ProductAPI,selected:string[],done:()=>void}) {
  const w=api.s.world,[department,setDepartment]=useState(w.departments[0].id),[address,setAddress]=useState('');
  const items=selected.filter(id=>w.cart[id]).map(id=>api.d.objects[id]);
  return <><PageHead title="确认部门订单" description="每个部门单独下单；本环境仅生成模拟订单，不发生实际扣款。"/><section className="purchase-panel"><label>采购部门<select aria-label="采购部门" value={department} onChange={e=>{setDepartment(e.target.value);setAddress('');}}>{w.departments.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>收货地址<input aria-label="收货地址" value={address} onChange={e=>setAddress(e.target.value)}/></label><button onClick={()=>setAddress(w.departments.find((d:any)=>d.id===department).address)}>填入部门地址</button><div className="purchase-order-lines">{items.map(p=><div key={p.id}><strong>{p.record_code} · {p.name}</strong><span>{p.spec} · {w.cart[p.id]} 件 × ¥{p.price}</span><b>¥{w.cart[p.id]*p.price}</b></div>)}</div><p>合计：¥{items.reduce((total,p)=>total+p.price*w.cart[p.id],0)}</p><button className="product-primary" disabled={api.busy||!address||!items.length} onClick={async()=>{if(await send(api,'order.place','',{department,address,lines:Object.fromEntries(items.map(p=>[p.id,w.cart[p.id]]))}))done();}}>确认模拟下单</button></section></>;
}

function Handover({api,request,download}:{api:ProductAPI,request:any,download:(id:string)=>void}) {
  const w=api.s.world,saved=w.handovers[request.id],receipts=w.receipts.filter((r:any)=>r.request===request.id);
  const [rows,setRows]=useState<any[]>(saved?.rows||request.products.map((sku:string)=>({sku,cart_quantity:0,favorite:false}))),[recipient,setRecipient]=useState('');
  const dirty=!saved||signature(rows)!==signature(saved.rows),stale=!!saved&&signature(saved.rows)!==signature(currentRows(w,request));
  function edit(sku:string,key:string,value:any){setRows(old=>old.map(r=>r.sku===sku?{...r,[key]:value}:r));}
  const person=w.people.find((p:any)=>p.id===request.recipient);
  return <><PageHead title={request.title+' · 交接单'} description={'按清单顺序核对全部商品。交接联系人：'+person.name+'；清单 '+request.id}/><section className="purchase-panel"><button disabled={!!receipts.length} onClick={()=>setRows(currentRows(w,request))}>读取当前商品状态</button><table className="purchase-table"><thead><tr><th>商品</th><th>购物车数量</th><th>已收藏</th><th>核对来源</th></tr></thead><tbody>{rows.map(row=>{const p=api.d.objects[row.sku];return <tr key={row.sku}><td><strong>{p.name}</strong><small>{p.record_code} · {p.spec}</small></td><td><input type="number" min="0" aria-label={'交接数量 '+p.record_code} value={row.cart_quantity} disabled={!!receipts.length} onChange={e=>edit(row.sku,'cart_quantity',Number(e.target.value))}/></td><td><input type="checkbox" aria-label={'交接收藏 '+p.record_code} checked={row.favorite} disabled={!!receipts.length} onChange={e=>edit(row.sku,'favorite',e.target.checked)}/></td><td><a href={api.applicationLink?.('shop',{product:row.sku})}>查看商品 {p.record_code}</a></td></tr>;})}</tbody></table><div className="product-actions"><button className="product-primary" disabled={api.busy||!!receipts.length} onClick={()=>send(api,'handover.save',request.id,{rows})}>保存交接单</button>{saved&&<button disabled={api.busy||!!receipts.length} onClick={()=>send(api,'handover.delete',request.id)}>删除交接单</button>}</div>{stale&&<p role="alert">商品状态已经变化，请撤回已发送通知并重新核对交接单。</p>}{dirty&&<p>交接明细有待保存内容。</p>}</section>{saved&&<section className="purchase-panel"><h2>已保存的交接单</h2><button onClick={()=>download('handover-'+request.id)}>下载采购交接单</button><pre className="purchase-document">{saved.body}</pre></section>}<section className="purchase-panel"><h2>发送给下一班采购人员</h2><p>请核对收件人及交接明细。已发送的交接单需先撤回才能修改。</p><div className="product-actions"><label>交接收件人<select aria-label="交接收件人" value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">请选择联系人</option>{w.people.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {w.departments.find((d:any)=>d.id===p.department).name}</option>)}</select></label><button disabled={api.busy||!recipient||dirty||stale||!!receipts.length} onClick={()=>send(api,'handover.send',request.id,{recipient:Number(recipient)})}>发送采购交接单</button><a href={api.applicationLink?.('im')}>打开团队采购消息 →</a></div>{receipts.map((r:any)=><div className="product-actions" data-shopping-receipt={r.id} key={r.id}><span>已发送给 {w.people.find((p:any)=>p.id===r.recipient).name} · {r.id}</span><button disabled={api.busy} onClick={()=>send(api,'receipt.withdraw',r.id)}>撤回交接通知</button></div>)}</section></>;
}

export function ShopProjects({api}:{api:ProductAPI}) {
  const {s,d}=api,w=s.world,queryParams=new URLSearchParams(location.search),isPurchase=s.task_id===52;
  const [page,setPage]=useState(queryParams.has('product')?'detail':queryParams.has('handover')?'handover':queryParams.has('request')?'request':queryParams.has('order')?'order':queryParams.has('file')?'file':'home');
  const [productId,setProductId]=useState(queryParams.get('product')||''),[requestId,setRequestId]=useState(queryParams.get('request')||queryParams.get('handover')||w.requests[0]?.id||''),[orderId,setOrderId]=useState(queryParams.get('order')||'');
  const [category,setCategory]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState('');
  const products=s.items.map((p:any)=>d.objects[p.id]),active=d.objects[productId],request=w.requests.find((r:any)=>r.id===requestId),order=w.orders[orderId];
  function nav(p:string){setPage(p);setQuery('');setCategory('');setError('');api.clearNotice?.();}
  function open(id:string){setProductId(id);nav('detail');}
  async function download(id:string){try{await api.downloadFile?.(id,d.files[id].name);}catch(e){setError(String(e));}}
  const filtered=products.filter((p:any)=>(!query||[p.name,p.spec,p.record_code,p.vendor].some(x=>x.includes(query)))&&(!category||p.category===category)&&(page!=='cart'||w.cart[p.id])&&(page!=='favorites'||w.favorites.includes(p.id))&&(page!=='request'||request?.products.includes(p.id)));
  function cards(items:any[]){return <div className="purchase-grid">{items.map((p:any)=><article className="purchase-product" data-product={p.id} key={p.id}><ProductArt item={p} index={0}/><div><small>{p.record_code} · {p.vendor}</small><h3>{p.name}</h3><p>{p.spec}</p><div className="purchase-tags">{p.tags.map((t:string)=><span key={t}>{t}</span>)}</div><p>评分 {p.rating.toFixed(1)} · 初始库存 {p.stock} 件</p><p>当前库存 {w.stock[p.id]} 件 · 购物车 {w.cart[p.id]||0} 件{w.favorites.includes(p.id)?' · 已收藏':''}</p><div className="purchase-price"><b>¥{p.price}</b><button onClick={()=>open(p.id)}>查看商品</button></div>{page==='cart'&&isPurchase&&<label className="purchase-select"><input type="checkbox" aria-label={'结算商品 '+p.record_code} checked={selected.includes(p.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/>加入本次部门结算</label>}</div></article>)}</div>;}
  return <Frame brand="拾物商店" accent="#a04e35" page={page} navigate={nav} tabs={[["home","发现好物"],["requests",isPurchase?"部门采购需求":"采购整理通知"],["products","商品目录"],["cart","购物车"],["favorites","我的收藏"],...(isPurchase?[["orders","我的订单"] as [string,string]]:[["handovers","采购交接"] as [string,string]])]} tools={<><input aria-label="搜索商品" placeholder="搜索名称、规格或编号" value={query} onChange={e=>{setQuery(e.target.value);setCategory('');setPage('products');}}/>{(!isPurchase||s.cross_platform)&&<a href={api.applicationLink?.('im')}>团队采购消息 →</a>}</>}><main className="product-main purchase-workspace"><Notice api={api}/>{error&&<p role="alert">{error}</p>}
    {page==='home'&&<><section className="shop-hero"><div><span>EVERYDAY, WELL MADE.</span><h1>让日常，<br/>多一点称心。</h1><p>为通勤、工作与生活挑选实用好物。</p><button className="product-primary" onClick={()=>nav('requests')}>{isPurchase?'查看部门采购需求':'查看本期整理通知'}</button></div><ProductArt item={products[0]} index={0}/></section><section className="purchase-panel" aria-label="工作范围"><h2>{isPurchase?'为同事准备合适的办公用品':'把采购进度交接清楚'}</h2><p>{w.brief}</p></section><PageHead title="本期精选"/>{cards(products.slice(0,3))}</>}
    {page==='requests'&&<><PageHead title={isPurchase?'部门采购需求':'采购整理通知'}/><section className="purchase-panel"><p>{w.brief}</p>{(!isPurchase||s.cross_platform)&&<a href={api.applicationLink?.('im')}>查看原始采购通知 →</a>}</section>{isPurchase?w.departments.map((dep:any)=><section className="purchase-panel" key={dep.id} data-department={dep.id}><h2>{dep.name}</h2><p>收货地址：{dep.address}</p>{w.needs.filter((n:any)=>n.department===dep.id).map((need:any)=><div className="purchase-need" data-need={need.id} key={need.id}><div><strong>{need.name} · {need.spec}</strong><p>{need.id} · {need.quantity} 件 · 单价不超过 ¥{need.budget}</p></div><button onClick={()=>{nav('products');setCategory(need.category);}}>查看候选商品</button></div>)}</section>):w.requests.map((r:any)=><section className="purchase-panel" data-request={r.id} key={r.id}><h2>{r.title}</h2><p>{r.id} · 指定标签：{r.label} · 联系人：{w.people.find((p:any)=>p.id===r.recipient).name}</p><p>{r.products.map((id:string)=>d.objects[id].record_code+' × '+r.quantities[id]).join('、')}</p><button onClick={()=>{setRequestId(r.id);nav('request');}}>打开整理清单</button></section>)}</>}
    {page==='request'&&request&&<><PageHead title={request.title} description={request.id+' · 指定标签：'+request.label+' · 仅处理下方清单中的商品'}/><section className="purchase-panel"><p>新增入车数量：{request.products.map((id:string)=>d.objects[id].record_code+' × '+request.quantities[id]).join('、')}。已在车内的不重复添加。</p><button onClick={()=>nav('handover')}>填写本清单交接单</button></section>{cards(filtered)}</>}
    {['products','cart','favorites'].includes(page)&&<><PageHead title={page==='cart'?'购物车':page==='favorites'?'我的收藏':'商品目录'} description={page==='products'?'按商品编号和规格核对，初始库存是本期选择的比较依据。':''}/>{page==='products'&&<label className="purchase-category">商品类别<select aria-label="商品类别" value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部类别</option>{Array.from(new Set(products.map((p:any)=>p.category))).map((id:any)=><option key={id} value={id}>{products.find((p:any)=>p.category===id).name}</option>)}</select></label>}{page==='cart'&&isPurchase&&<section className="purchase-panel"><p>勾选同一部门需要的商品，再按部门地址确认订单。未勾选的商品留在购物车。</p><button className="product-primary" disabled={!selected.some(id=>w.cart[id])} onClick={()=>nav('checkout')}>按部门结算</button></section>}{cards(filtered)}{!filtered.length&&<p>此处暂无商品。</p>}</>}
    {page==='detail'&&(active?<><button className="product-back" onClick={()=>nav('products')}>← 商品目录</button><ProductDetail key={active.id} api={api} item={active}/></>:<p role="alert">商品不存在</p>)}
    {page==='checkout'&&<Checkout api={api} selected={selected} done={()=>{setSelected([]);nav('orders');}}/>}
    {page==='orders'&&<><PageHead title="我的订单" description="已确认的部门订单与可下载回执。取消模拟订单会把商品和数量放回购物车。"/>{values(w.orders).map(o=><section className="purchase-panel" data-order={o.id} key={o.id}><h2>{o.id} · {w.departments.find((dep:any)=>dep.id===o.department).name}</h2><p>{o.address}</p><p>{Object.keys(o.lines).length} 种商品 · {o.confirmation}</p><button onClick={()=>{setOrderId(o.id);nav('order');}}>查看订单回执</button></section>)}{!values(w.orders).length&&<p>还没有已确认的订单。</p>}</>}
    {page==='order'&&(order?<section className="purchase-panel"><PageHead title={order.id}/><div className="product-actions"><button onClick={()=>download('order-'+order.id)}>下载订单回执</button><a href={api.applicationLink?.('shop',{file:'order-'+order.id})}>打开订单文件</a><button disabled={api.busy} onClick={async()=>{if(await send(api,'order.cancel',order.id))nav('orders');}}>取消模拟订单</button></div><pre className="purchase-document">{readFile(d.files['order-'+order.id])}</pre></section>:<p role="alert">订单不存在或已取消</p>)}
    {page==='handovers'&&<><PageHead title="采购交接" description="按清单分别保存明细，再发送给对应联系人。"/>{w.requests.map((r:any)=><section className="purchase-panel" data-handover={r.id} key={r.id}><h2>{r.title}</h2><p>{r.id} · {w.handovers[r.id]?'已保存交接单':'尚未填写'}</p><button onClick={()=>{setRequestId(r.id);nav('handover');}}>编辑交接单</button></section>)}</>}
    {page==='handover'&&(request?<Handover key={request.id} api={api} request={request} download={download}/>:<p role="alert">采购清单不存在</p>)}
    {page==='file'&&(d.files[queryParams.get('file')||'']?<section className="purchase-panel"><PageHead title={d.files[queryParams.get('file')!].name}/><pre className="purchase-document">{readFile(d.files[queryParams.get('file')!])}</pre></section>:<p role="alert">文件不存在</p>)}
  </main></Frame>;
}
