import {useState} from 'react';
import {Frame,PageHead,Notice,type ProductAPI} from './kit';
const entries=(x:any):any[]=>Object.values(x);
const decode=(file:any)=>file?new TextDecoder().decode(Uint8Array.from(atob(file.content),(c)=>c.charCodeAt(0))):'';
const stamp=(s:string)=>s.replace('T',' ').replace('+08:00','');
const signature=(b:any)=>JSON.stringify([b.slot,b.route,b.cost_center,b.contact,b.passengers.map((p:any)=>[p.id,p.full_name,p.document,p.contact])]);
const saved=(b:any)=>b.saved&&signature(b)===signature(b.saved);
export function TravelProjects({api}:{api:ProductAPI}) {
  const {s,d}=api,w=s.world,query=new URLSearchParams(location.search),isApproval=s.task_id===54;
  const slots=isApproval?w.requests:w.legs;
  const [page,setPage]=useState(query.has('booking')?'booking':query.has('file')?'file':query.has('request')?'request':'home');
  const [slot,setSlot]=useState(query.get('request')||slots[0].id),[bookingId,setBookingId]=useState(query.get('booking')||''),[error,setError]=useState('');
  const source=slots.find((r:any)=>r.id===slot),booking=w.bookings[bookingId];
  const person=(id:string)=>w.people.find((p:any)=>p.id===id);
  const command=(op:string,target='',data={})=>api.mutate(op,target,JSON.stringify(data));
  const link=(q:Record<string,string>)=>api.applicationLink?.('travel',q)||'#';
  function nav(p:string){setPage(p);setError('');api.clearNotice?.();}
  function routes(id:string){setSlot(id);nav('routes');}
  async function create(route:string){const id='BOOK-'+String(s.next_booking||1).padStart(3,'0');if(await command('booking.create',slot,{route})){setBookingId(id);nav('booking');}}
  async function download(id:string){try{await api.downloadFile?.(id,d.files[id].name);}catch(e){setError(String(e));}}
  function Profile({p}:{p:any}){const [name,setName]=useState(w.profiles[p.id].full_name);return <article className="trip-panel" data-person={p.id}><h2>{p.name}</h2><p>{p.id} · 模拟证件 {p.document}</p><dl className="trip-facts"><dt>姓</dt><dd>{p.surname}</dd><dt>名</dt><dd>{p.given_name}</dd><dt>联系邮箱</dt><dd>{p.contact}</dd></dl><label>旅客显示姓名<input aria-label={'旅客显示姓名 '+p.id} readOnly={s.task_id!==44} value={name} onChange={e=>setName(e.target.value)}/></label>{s.task_id===44&&<button disabled={api.busy||!name} onClick={()=>command('profile.save',p.id,{full_name:name})}>保存旅客资料</button>}</article>;}
  function Slot({r}:{r:any}){
    const [selected,setSelected]=useState(w.approvals[r.id]||'');const ids=isApproval?[r.person]:r.passengers;
    return <article className="trip-panel" data-slot={r.id}><h2>{isApproval?r.id+' · '+r.purpose:r.name}</h2>{!isApproval&&s.task_id===51&&<p>会议：{stamp(r.meeting_start)} 至 {stamp(r.meeting_end)} · 单段预算 ¥{w.budget}</p>}<ul>{ids.map((id:string)=><li key={id}>{id} · {person(id).name} · 模拟证件 {person(id).document}</li>)}</ul><p>成本中心：{r.cost_center} · 联系邮箱：{r.contact}</p>{isApproval&&<p>申请车次：{d.objects[r.route].record_code} · ¥{d.objects[r.route].price} · 换乘 {d.objects[r.route].transfers} 次</p>}<button onClick={()=>routes(r.id)}>查看候选车次</button>{isApproval&&<><div className="trip-actions"><label>回填预订号<select aria-label={'回填预订号 '+r.id} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">选择已确认预订</option>{entries(w.bookings).filter(b=>b.status==='confirmed').map(b=><option key={b.id} value={b.id}>{b.id} · {b.slot} · {d.objects[b.route].record_code}</option>)}</select></label><button disabled={api.busy||!selected} onClick={()=>command('approval.record',r.id,{booking:selected})}>保存申请回填</button>{w.approvals[r.id]&&<button disabled={api.busy} onClick={()=>command('approval.clear',r.id)}>清除回填</button>}</div><p className="trip-status">{w.approvals[r.id]?'已回填：'+w.approvals[r.id]:'待处理'}</p></>}</article>;
  }
  function BookingEditor({b}:{b:any}){
    const request=slots.find((r:any)=>r.id===b.slot),route=d.objects[b.route];
    const [rows,setRows]=useState<any[]>(b.passengers),[center,setCenter]=useState(b.cost_center),[contact,setContact]=useState(b.contact),[recipient,setRecipient]=useState('');
    const dirty=center!==b.cost_center||contact!==b.contact||JSON.stringify(rows.map(p=>[p.id,p.full_name,p.document,p.contact]))!==JSON.stringify(b.passengers.map((p:any)=>[p.id,p.full_name,p.document,p.contact]));
    function select(id:string,on:boolean){setRows(old=>on?[...old,{id,...w.profiles[id]}]:old.filter(p=>p.id!==id));}
    function edit(id:string,key:string,value:string){setRows(old=>old.map(p=>p.id===id?{...p,[key]:value}:p));}
    return <><PageHead title={b.id} description={`${route.record_code} · ${route.origin} → ${route.destination} · ${b.status==='confirmed'?'已确认':'预订草稿'}`}/><section className="trip-panel"><h2>车次与申请</h2><p>{stamp(route.depart_at)} → {stamp(route.arrive_at)} · {route.duration} 分钟 · ¥{route.price} / 人</p><p>关联：{b.slot} · 成本中心要求：{request.cost_center} · 联系邮箱：{request.contact}</p><p>要求旅客：{(isApproval?[request.person]:request.passengers).join('、')}</p></section>
      <section className="trip-panel"><h2>乘客与联系资料</h2><p>选择旅客会填入已保存的常用旅客资料，请逐项核对编号、姓名与模拟证件。</p><div className="trip-people-select">{w.people.map((p:any)=><label key={p.id}><input type="checkbox" aria-label={'选择旅客 '+p.id} disabled={b.status==='confirmed'} checked={rows.some(r=>r.id===p.id)} onChange={e=>select(p.id,e.target.checked)}/><span>{p.id} · {p.name}<small>{p.document}</small></span></label>)}</div>{rows.map(p=><fieldset data-passenger={p.id} className="trip-passenger" key={p.id}><legend>{p.id} · {person(p.id).name}</legend><label>显示姓名<input aria-label={'预订姓名 '+p.id} readOnly={b.status==='confirmed'} value={p.full_name} onChange={e=>edit(p.id,'full_name',e.target.value)}/></label><label>模拟证件号<input aria-label={'预订证件 '+p.id} readOnly={b.status==='confirmed'} value={p.document} onChange={e=>edit(p.id,'document',e.target.value)}/></label><label>旅客联系邮箱<input aria-label={'旅客邮箱 '+p.id} readOnly={b.status==='confirmed'} value={p.contact} onChange={e=>edit(p.id,'contact',e.target.value)}/></label></fieldset>)}<div className="trip-two-fields"><label>成本中心<select aria-label="成本中心" disabled={b.status==='confirmed'} value={center} onChange={e=>setCenter(e.target.value)}><option value="">请选择成本中心</option>{w.cost_centers.map((c:string)=><option key={c}>{c}</option>)}</select></label><label>预订联系邮箱<input aria-label="预订联系邮箱" readOnly={b.status==='confirmed'} value={contact} onChange={e=>setContact(e.target.value)}/></label></div>{b.status==='draft'&&<><button onClick={()=>{setCenter(request.cost_center);setContact(request.contact);}}>填入申请联系方式</button><div className="trip-actions"><button disabled={api.busy||!rows.length||!center||!contact} onClick={()=>command('booking.passengers',b.id,{passengers:rows,cost_center:center,contact})}>更新乘客资料</button><button className="product-primary" disabled={api.busy||dirty||!b.passengers.length} onClick={()=>command('booking.save',b.id)}>保存预订草稿</button>{s.task_id!==44&&<button disabled={api.busy||dirty||!saved(b)} onClick={()=>command('booking.confirm',b.id)}>确认模拟预订</button>}</div><p>{dirty?'有未保存的乘客资料，请先更新资料。':saved(b)?'预订资料已保存。':'请保存预订草稿。'}</p></>}{b.status==='confirmed'&&<p className="trip-status">模拟确认号：{b.confirmation}</p>}<button disabled={api.busy} onClick={async()=>{if(await command('booking.delete',b.id))nav('bookings');}}>取消并移除预订</button></section>
      {d.files['booking-'+b.id]&&<section className="trip-panel"><h2>行程单文件</h2><div className="trip-actions"><a href={link({file:'booking-'+b.id})}>打开预订行程单</a><button onClick={()=>download('booking-'+b.id)}>下载预订行程单</button></div><pre className="trip-document">{decode(d.files['booking-'+b.id])}</pre></section>}
      {isApproval&&b.status==='confirmed'&&<section className="trip-panel"><h2>发送行程单</h2><p>申请人：{person(request.person).name} · {request.person}</p><div className="trip-actions"><label>行程单收件人<select aria-label="行程单收件人" value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">选择联系人</option>{w.people.map((p:any)=><option key={p.id} value={p.im}>{p.name} · {p.id}</option>)}</select></label><button disabled={api.busy||!recipient} onClick={()=>command('receipt.send',b.id,{recipient:Number(recipient)})}>发送行程单</button><a href={api.applicationLink?.('im')}>打开团队消息 →</a></div>{w.receipts.filter((r:any)=>r.booking===b.id).map((r:any)=><div className="trip-actions" data-travel-receipt={r.id} key={r.id}><span>{r.id} · 已发送给 {w.people.find((p:any)=>p.im===r.recipient)?.name}</span><button disabled={api.busy} onClick={()=>command('receipt.withdraw',r.id)}>撤回行程通知</button></div>)}<button onClick={()=>nav('plan')}>返回审批申请</button></section>}
    </>;
  }
  function Itinerary(){const [chosen,setChosen]=useState<string[]>(w.itinerary?.bookings||[]);return <><PageHead title="完整出差行程单" description="选取本次预订，系统按实际出发时间排列并保存文件。"/><section className="trip-panel">{entries(w.bookings).map(b=><label className="trip-booking-choice" key={b.id}><input type="checkbox" aria-label={'行程单预订 '+b.id} checked={chosen.includes(b.id)} onChange={e=>setChosen(old=>e.target.checked?[...old,b.id]:old.filter(id=>id!==b.id))}/><span>{b.id} · {d.objects[b.route].record_code} · {b.status==='confirmed'?'已确认':'草稿'} · {b.passengers.length} 位旅客</span></label>)}<div className="trip-actions"><button className="product-primary" disabled={api.busy||!chosen.length} onClick={()=>command('itinerary.save','',{bookings:chosen})}>保存合并行程单</button>{w.itinerary&&<button disabled={api.busy} onClick={()=>command('itinerary.clear')}>清除合并行程单</button>}</div></section>{w.itinerary&&<section className="trip-panel"><h2>已保存行程单</h2><div className="trip-actions"><a href={link({file:'travel-itinerary'})}>打开完整行程文件</a><button onClick={()=>download('travel-itinerary')}>下载完整行程单</button></div><pre className="trip-document">{w.itinerary.body}</pre></section>}</>;}
  const file=d.files[query.get('file')||''];
  return <Frame brand="行远旅行" accent="#087d86" page={page} navigate={nav} tabs={[["home","旅行首页"],["plan",isApproval?"审批申请":"差旅安排"],["routes","车次查询"],["passengers","常用旅客"],["bookings","我的订单"],["itinerary","出差行程单"]]} tools={(s.task_id!==51||s.cross_platform)&&<a href={api.applicationLink?.('im')}>团队消息 ↗</a>}><main className="product-main trip-workspace"><Notice api={api}/>{error&&<p role="alert">{error}</p>}
      {page==='home'&&<><section className="travel-hero"><span>JOURNEYS THAT STAY WITH YOU</span><h1>下一站，去看看。</h1><p>核对出行资料，让每一段旅程都有清楚的安排。</p><div className="travel-search"><label>出发城市<b>北京</b></label><span>⇄</span><label>出行安排<b>{isApproval?'本期差旅审批':s.task_id===51?'济南 · 南京 · 上海':'南京 · 上海'}</b></label><button className="product-primary" onClick={()=>nav('plan')}>{isApproval?'查看审批申请':'查看差旅安排'}</button></div></section><section className="trip-panel" aria-label="工作范围"><h2>{s.execution.assignment}</h2><p>{w.brief}</p></section><div className="travel-services"><button onClick={()=>nav('passengers')}><span>◎</span><h3>常用旅客</h3><p>核对旅客编号与出行姓名</p></button><button onClick={()=>nav('bookings')}><span>▦</span><h3>我的订单</h3><p>查看预订与确认号</p></button><button onClick={()=>nav('itinerary')}><span>⇆</span><h3>出差行程单</h3><p>保存本次完整出行安排</p></button></div></>}
      {(page==='plan'||page==='request')&&<><PageHead title={isApproval?'本期差旅审批':'差旅安排'} description="时间均为北京时间；证件及预订均为模拟资料。"/><section className="trip-panel"><p>{w.brief}</p>{s.task_id!==51&&<a href={api.applicationLink?.('im')}>查看团队出行通知 →</a>}{w.notices.map((n:any)=><article className="trip-notice" key={n.id}><h3>{n.title}</h3><p>{n.body}</p></article>)}</section>{slots.filter((r:any)=>page!=='request'||r.id===slot).map((r:any)=><Slot key={r.id} r={r}/>)}</>}
      {page==='routes'&&<><PageHead title="车次查询" description="比较候选车次与会议时间；出发、到达均以北京时间显示。"/><section className="trip-panel"><label>行程或申请<select aria-label="行程或申请" value={slot} onChange={e=>setSlot(e.target.value)}>{slots.map((r:any)=><option key={r.id} value={r.id}>{r.name||r.id+' · '+r.purpose}</option>)}</select></label><p>{w.brief}</p>{s.task_id===51&&<p>本段会议：{stamp(source.meeting_start)} 至 {stamp(source.meeting_end)}</p>}</section><div className="trip-routes">{(isApproval?[source.route]:source.candidates).map((id:string)=>{const r=d.objects[id],existing=entries(w.bookings).find(b=>b.slot===slot);return <article className="trip-route" data-route={id} key={id}><div><span className="product-eyebrow">{r.record_code} · {r.seat}</span><h2>{r.origin} → {r.destination}</h2><p>{stamp(r.depart_at)} → {stamp(r.arrive_at)}</p><p>{r.duration} 分钟 · 换乘 {r.transfers} 次</p></div><div><strong>¥{r.price}</strong>{existing?<button onClick={()=>{setBookingId(existing.id);nav('booking');}}>打开本段预订</button>:<button className="product-primary" disabled={api.busy} onClick={()=>create(id)}>填写预订资料</button>}</div></article>;})}</div></>}
      {page==='passengers'&&<><PageHead title="常用旅客" description="姓名相同的旅客须按编号与模拟证件号区分。"/>{w.people.map((p:any)=><Profile key={p.id} p={p}/>)}</>}
      {page==='booking'&&(booking?<BookingEditor key={booking.id} b={booking}/>:<p role="alert">预订不存在或已取消</p>)}
      {page==='bookings'&&<><PageHead title="我的订单" description="本次工作区的预订草稿与模拟确认记录。"/>{!entries(w.bookings).length&&<p>还没有预订，请从差旅安排中选择车次。</p>}{entries(w.bookings).map(b=><article className="trip-panel" data-booking={b.id} key={b.id}><h2>{b.id} · {d.objects[b.route].origin} → {d.objects[b.route].destination}</h2><p>{b.slot} · {d.objects[b.route].record_code} · {b.passengers.length} 位旅客 · {b.status==='confirmed'?'已确认 '+b.confirmation:'预订草稿'}</p><button onClick={()=>{setBookingId(b.id);nav('booking');}}>查看预订详情</button></article>)}</>}
      {page==='itinerary'&&<Itinerary/>}
      {page==='file'&&(file?<section className="trip-panel"><PageHead title={file.name} action={<button onClick={()=>download(query.get('file')!)}>下载行程文件</button>}/><pre className="trip-document">{decode(file)}</pre></section>:<p role="alert">行程文件不存在</p>)}
    </main></Frame>;
}
