# Generated by Django 5.2.12 on 2026-03-18 03:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, db_index=True, default='', help_text='手机号', max_length=20)),
                ('avatar', models.URLField(blank=True, default='', help_text='头像 URL', max_length=500)),
                ('presence', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌'), ('away', '离开'), ('invisible', '隐身')], default='offline', help_text='在线状态', max_length=10)),
                ('status_text', models.CharField(blank=True, default='', help_text='自定义状态文本', max_length=100)),
                ('status_emoji', models.CharField(blank=True, default='', help_text='状态 Emoji', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, help_text='最后在线时间', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'chat_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', '私聊'), ('group', '群聊'), ('ai', 'AI 对话')], max_length=10)),
                ('name', models.CharField(blank=True, default='', help_text='会话名称（群聊使用，私聊为空）', max_length=50)),
                ('avatar', models.URLField(blank=True, default='', help_text='群头像 URL', max_length=500)),
                ('is_dissolved', models.BooleanField(default=False, help_text='群聊是否已解散')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='群主（仅群聊有值）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('member', '普通成员')], default='member', help_text='成员角色（仅群聊有意义）', max_length=10)),
                ('nickname', models.CharField(blank=True, default='', help_text='群昵称', max_length=30)),
                ('is_pinned', models.BooleanField(default=False, help_text='是否置顶该会话')),
                ('is_muted', models.BooleanField(default=False, help_text='是否设置免打扰')),
                ('is_deleted', models.BooleanField(default=False, help_text='用户是否删除了该会话（收到新消息时自动恢复）')),
                ('read_index', models.BigIntegerField(default=0, help_text='该用户在此会话中已读到的最新 msg_id')),
                ('read_at', models.DateTimeField(blank=True, help_text='最后一次标记已读的时间', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation_member',
            },
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分组名称', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_friend_group',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', help_text='验证消息', max_length=200)),
                ('source', models.CharField(blank=True, default='search', help_text='来源: search / group:{conv_id} / contact_card:{msg_id}', max_length=100)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已同意'), ('rejected', '已拒绝')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_friend_request',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, default='', help_text='好友备注名', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friended_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='所属好友分组，null 表示未分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendships', to='chat.friendgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_friendship',
            },
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='公告内容', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='chat.conversation')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_group_announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.conversation')),
                ('invitee', models.ForeignKey(help_text='被邀请者', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='邀请者', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='审核人（群主或管理员）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_group_invitation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_msg_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='客户端生成的消息 UUID，用于幂等去重')),
                ('type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('audio', '语音'), ('file', '文件'), ('code', '代码'), ('contact_card', '好友名片'), ('forward', '合并转发'), ('system', '系统消息')], default='text', max_length=15)),
                ('content', models.JSONField(default=dict, help_text='消息内容，JSON 格式，结构随 type 不同')),
                ('is_recalled', models.BooleanField(default=False, help_text='是否已撤回')),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('mentions', models.ManyToManyField(blank=True, help_text='被 @ 提及的用户列表', related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, help_text='回复的目标消息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('sender', models.ForeignKey(help_text='发送者（已注销用户为 null）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', help_text='收藏备注', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(help_text='消息所在会话（冗余字段，方便查询）', on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='chat.message')),
            ],
            options={
                'db_table': 'chat_bookmark',
            },
        ),
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_deletion',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Emoji 字符', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_reaction',
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='被拉黑的 refresh_token')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token 原始过期时间，过期后可以清理该记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_token_blacklist',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, help_text='文件唯一标识', max_length=50, unique=True)),
                ('url', models.URLField(help_text='文件访问 URL', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='缩略图 URL（仅图片和视频）', max_length=500)),
                ('filename', models.CharField(help_text='原始文件名', max_length=255)),
                ('size', models.BigIntegerField(help_text='文件大小（字节）')),
                ('mime_type', models.CharField(help_text='MIME 类型', max_length=100)),
                ('width', models.IntegerField(blank=True, help_text='图片/视频宽度（像素）', null=True)),
                ('height', models.IntegerField(blank=True, help_text='图片/视频高度（像素）', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='音频/视频时长（秒）', null=True)),
                ('purpose', models.CharField(choices=[('message', '消息附件'), ('avatar', '头像')], default='message', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_uploaded_file',
            },
        ),
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_search_by_username', models.BooleanField(default=True, help_text='是否允许通过用户名被搜索到')),
                ('allow_search_by_email', models.BooleanField(default=True, help_text='是否允许通过邮箱被搜索到')),
                ('allow_search_by_phone', models.BooleanField(default=True, help_text='是否允许通过手机号被搜索到')),
                ('allow_add_from_group', models.BooleanField(default=True, help_text='是否允许群聊内成员直接添加好友')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_user_privacy',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='验证码发送到的邮箱地址', max_length=254)),
                ('code', models.CharField(help_text='6 位数字验证码', max_length=6)),
                ('purpose', models.CharField(choices=[('change_email', '修改邮箱'), ('change_password', '修改密码'), ('bind_email', '绑定新邮箱')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='过期时间（创建后 5 分钟）')),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_verify_code',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist', to=settings.AUTH_USER_MODEL)),
                ('whitelisted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_whitelist',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_blacklist',
                'unique_together': {('user', 'blocked_user')},
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type'], name='chat_conver_type_857bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='chat_conver_updated_09e193_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'is_deleted'], name='chat_conver_user_id_53371c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'is_pinned'], name='chat_conver_user_id_e5e99e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='friendgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['to_user', 'status'], name='chat_friend_to_user_1eb148_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_user', 'status'], name='chat_friend_from_us_2d9b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user', 'friend')},
        ),
        migrations.AddIndex(
            model_name='groupannouncement',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_group__convers_b90d84_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['conversation', 'status'], name='chat_group__convers_ef859b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-id'], name='chat_messag_convers_1a2a58_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sender', 'client_msg_id'], name='chat_messag_convers_082c09_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', '-created_at'], name='chat_bookma_user_id_f4a6c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='messagedeletion',
            unique_together={('user', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['token'], name='chat_token__token_637e10_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['expires_at'], name='chat_token__expires_ba3224_idx'),
        ),
        migrations.AddIndex(
            model_name='verifycode',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='chat_verify_user_id_df626d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whitelist',
            unique_together={('user', 'whitelisted_user')},
        ),
    ]
