# Generated by Django 5.1.6 on 2026-05-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationmember_is_removed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyCode',
        ),
    ]
