# Generated by Django 5.1.6 on 2026-05-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_verifycode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recalled_by',
            field=models.ForeignKey(
                blank=True,
                help_text='执行撤回操作的用户',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='recalled_messages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='ReactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('add', '添加'), ('remove', '取消')], max_length=10)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_events', to='chat.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_reaction_event',
            },
        ),
        migrations.AddIndex(
            model_name='reactionevent',
            index=models.Index(fields=['message', 'created_at'], name='chat_reacti_message_abbb05_idx'),
        ),
        migrations.AddIndex(
            model_name='reactionevent',
            index=models.Index(fields=['created_at'], name='chat_reacti_created_c6b5f3_idx'),
        ),
    ]
